### ISSUE TITLE
Issue with SDL3 SDL_SetRelativeMouseMode() not hiding the cursor on Ubuntu 24.04.1

### ISSUE THREAD

**Issue by qqiu** [libsdl-org/SDL#10946]
I am experiencing an issue where SDL_SetRelativeMouseMode() does not hide the cursor as expected on Ubuntu 24.04.1. Despite enabling relative mouse mode, the cursor remains visible in the center.

System Info:
    SDL version: SDL3
    OS: Ubuntu 24.04.1 (updated to the latest version)
    Window manager: GNOME
    Graphics driver: i915

I also tried using the testrelative test program to reproduce the issue but was unsure which parameters to use and what the expected test results should look like.

**Comment by Kontrabant** [comment]
Are you using the latest SDL3 code?  There was a fix pushed for this issue some time ago.

**Comment by qqiu** [comment]
I still see the issue with the most recent version of the SDL3 code.

**Comment by qqiu** [comment]
Updating to the newest SDL3 code does resolve the problem.

Closed.

**Comment by qqiu-cyt** [comment]
@Kontrabant Could you point me to the fix for this issue? I'm looking for the issue number or commit ID.

**Comment by Kontrabant** [comment]
Sure, it was fixed with b0713a7d3047ca121c4257337da48cafbcbc44d4
