### ISSUE TITLE
 "Cannot open source file "unistd.h in SDL\src\SDL_utils.c"	

### ISSUE THREAD

**Issue by sandsc** [libsdl-org/SDL#11228]
commit  [9af5ff](https://github.com/libsdl-org/SDL/commit/9af5ffcfbec3f46702fd2913e85e1ff44d91228a) 's cause
build failed on windows.

**Comment by sezero** [comment]
https://github.com/libsdl-org/SDL/pull/11220 introduced suspicious `HAVE_xxx` to platform build configs, but the _possible_ reason may be the added detection of `gethostname` in cmake: is this with a cmake and clang-cl combination? In any case, linkage may possibly fail because we don't link to `ws2_32` by default either.

Maybe something like this would solve the issue for you?

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 1aff054..cffba38 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -982,6 +982,7 @@ if(SDL_LIBC)
     wcsnlen wcscmp wcsdup wcslcat wcslcpy wcslen wcsncmp wcsstr wcstol
   )
   if(WINDOWS)
+    unset(HAVE_GETHOSTNAME)
     list(APPEND symbols_to_check
       _strrev _ui64toa _uitoa _ultoa _wcsdup
     )
```

(CC: @TheSpydog, @madebr)

**Comment by sandsc** [comment]
> #11220 introduced suspicious `HAVE_xxx` to platform build configs, but the _possible_ reason may be the added detection of `gethostname` in cmake: is this with a cmake and clang-cl combination? In any case, linkage may possibly fail because we don't link to `ws2_32` by default either.
> 
> Maybe something like this would solve the issue for you?
> 
> ```diff
> diff --git a/CMakeLists.txt b/CMakeLists.txt
> index 1aff054..cffba38 100644
> --- a/CMakeLists.txt
> +++ b/CMakeLists.txt
> @@ -982,6 +982,7 @@ if(SDL_LIBC)
>      wcsnlen wcscmp wcsdup wcslcat wcslcpy wcslen wcsncmp wcsstr wcstol
>    )
>    if(WINDOWS)
> +    unset(HAVE_GETHOSTNAME)
>      list(APPEND symbols_to_check
>        _strrev _ui64toa _uitoa _ultoa _wcsdup
>      )
> ```
> 
> (CC: @TheSpydog, @madebr)

Thanks, but shouldn't it be placed after the symbol check? 
```
  foreach(_FN IN LISTS symbols_to_check)
    string(TOUPPER ${_FN} _UPPER)
    set(LIBC_HAS_VAR "LIBC_HAS_${_UPPER}")
    check_symbol_exists("${_FN}" "${available_headers}" ${LIBC_HAS_VAR})
    set(HAVE_${_UPPER} ${${LIBC_HAS_VAR}})
  endforeach()
```
this can solve problem temporarily.

**Comment by slouken** [comment]
@sandsc, are you using CMake or the Visual Studio solutions?

**Comment by slouken** [comment]
Can you provide the CMake configuration output?

**Comment by slouken** [comment]
@madebr, any ideas here?

**Comment by madebr** [comment]
I think the `<unistd.h>` include should be protected with a `#ifdef HAVE_UNISTD_H` macro, or `#if !(defined(SDL_PLATFORM_WIN32) || defined(SDL_PLATFORM_GDK))`.

**Comment by sezero** [comment]
Current git master might be good now

**Comment by slouken** [comment]
Fixed in https://github.com/libsdl-org/SDL/commit/18410c03ea084f05da43911261c2369ddeac15d7

**Comment by sezero** [comment]
@sandsc: please confirm that current git main branch behaves in your environment

**Comment by sandsc** [comment]
> @sandsc: please confirm that current git main branch behaves in your environment
after delete cache and reconfigure cmake, issue still exists.
![image](https://github.com/user-attachments/assets/bf7ae5e0-9df8-440d-b023-9c2f4d02899b)
>[cmake] -- SDL3 was configured with the following options:
[cmake] -- 
[cmake] -- Platform: Windows-10.0.19045
[cmake] -- 64-bit:   TRUE
[cmake] -- Compiler:  MSVC/14.41.34120/bin/Hostx64/x64/cl.exe
[cmake] -- Revision: SDL3-preview-3.1.3-180-gdd955332a
[cmake] -- Vendor:   
[cmake] -- 
[cmake] -- Subsystems:
[cmake] --   Audio:    OFF
[cmake] --   Video:    ON
[cmake] --   GPU:      ON
[cmake] --   Render:   ON
[cmake] --   Camera:   ON
[cmake] --   Joystick: OFF
[cmake] --   Haptic:   OFF
[cmake] --   Hidapi:   OFF
[cmake] --   Power:    OFF
[cmake] --   Sensor:   OFF
[cmake] --   Dialog:   ON
[cmake] -- 
[cmake] -- Options:
[cmake] --   SDL_ALSA                    (Wanted: OFF): OFF
[cmake] --   SDL_ALSA_SHARED             (Wanted: OFF): OFF
[cmake] --   SDL_ALTIVEC                 (Wanted: OFF): OFF
[cmake] --   SDL_ARMNEON                 (Wanted: OFF): OFF
[cmake] --   SDL_ARMSIMD                 (Wanted: OFF): OFF
[cmake] --   SDL_ASAN                    (Wanted: OFF): OFF
[cmake] --   SDL_ASSEMBLY                (Wanted: ON): ON
[cmake] --   SDL_ASSERTIONS              (Wanted: auto): auto
[cmake] --   SDL_AVX                     (Wanted: ON): ON
[cmake] --   SDL_AVX2                    (Wanted: ON): ON
[cmake] --   SDL_AVX512F                 (Wanted: ON): ON
[cmake] --   SDL_BACKGROUNDING_SIGNAL    (Wanted: OFF): OFF
[cmake] --   SDL_CCACHE                  (Wanted: OFF): OFF
[cmake] --   SDL_CLANG_TIDY              (Wanted: OFF): OFF
[cmake] --   SDL_CLOCK_GETTIME           (Wanted: OFF): OFF
[cmake] --   SDL_COCOA                   (Wanted: OFF): OFF
[cmake] --   SDL_DBUS                    (Wanted: OFF): OFF
[cmake] --   SDL_DIRECTX                 (Wanted: OFF): OFF
[cmake] --   SDL_DISABLE_INSTALL         (Wanted: ON): OFF
[cmake] --   SDL_DISABLE_UNINSTALL       (Wanted: ON): OFF
[cmake] --   SDL_DISKAUDIO               (Wanted: OFF): OFF
[cmake] --   SDL_DUMMYAUDIO              (Wanted: OFF): OFF
[cmake] --   SDL_DUMMYCAMERA             (Wanted: ON): ON
[cmake] --   SDL_DUMMYVIDEO              (Wanted: ON): ON
[cmake] --   SDL_EXAMPLES                (Wanted: OFF): OFF
[cmake] --   SDL_EXAMPLES_LINK_SHARED    (Wanted: OFF): OFF
[cmake] --   SDL_FOREGROUNDING_SIGNAL    (Wanted: OFF): OFF
[cmake] --   SDL_GCC_ATOMICS             (Wanted: OFF): OFF
[cmake] --   SDL_GPU_DXVK                (Wanted: OFF): OFF
[cmake] --   SDL_HIDAPI                  (Wanted: OFF): OFF
[cmake] --   SDL_HIDAPI_JOYSTICK         (Wanted: OFF): OFF
[cmake] --   SDL_HIDAPI_LIBUSB           (Wanted: OFF): OFF
[cmake] --   SDL_HIDAPI_LIBUSB_SHARED    (Wanted: OFF): OFF
[cmake] --   SDL_IBUS                    (Wanted: OFF): OFF
[cmake] --   SDL_INSTALL_TESTS           (Wanted: OFF): OFF
[cmake] --   SDL_JACK                    (Wanted: OFF): OFF
[cmake] --   SDL_JACK_SHARED             (Wanted: OFF): OFF
[cmake] --   SDL_KMSDRM                  (Wanted: OFF): OFF
[cmake] --   SDL_KMSDRM_SHARED           (Wanted: OFF): OFF
[cmake] --   SDL_LASX                    (Wanted: OFF): OFF
[cmake] --   SDL_LIBC                    (Wanted: ON): ON
[cmake] --   SDL_LIBICONV                (Wanted: OFF): OFF
[cmake] --   SDL_LIBUDEV                 (Wanted: ON): OFF
[cmake] --   SDL_LSX                     (Wanted: OFF): OFF
[cmake] --   SDL_METAL                   (Wanted: OFF): OFF
[cmake] --   SDL_MMX                     (Wanted: ON): OFF
[cmake] --   SDL_OFFSCREEN               (Wanted: ON): ON
[cmake] --   SDL_OPENGL                  (Wanted: ON): ON
[cmake] --   SDL_OPENGLES                (Wanted: ON): ON
[cmake] --   SDL_OSS                     (Wanted: OFF): OFF
[cmake] --   SDL_PIPEWIRE                (Wanted: OFF): OFF
[cmake] --   SDL_PIPEWIRE_SHARED         (Wanted: OFF): OFF
[cmake] --   SDL_PTHREADS                (Wanted: OFF): OFF
[cmake] --   SDL_PTHREADS_SEM            (Wanted: OFF): OFF
[cmake] --   SDL_PULSEAUDIO              (Wanted: OFF): OFF
[cmake] --   SDL_PULSEAUDIO_SHARED       (Wanted: OFF): OFF
[cmake] --   SDL_RENDER_D3D              (Wanted: OFF): OFF
[cmake] --   SDL_RENDER_D3D11            (Wanted: OFF): OFF
[cmake] --   SDL_RENDER_D3D12            (Wanted: OFF): OFF
[cmake] --   SDL_RENDER_GPU              (Wanted: ON): ON
[cmake] --   SDL_RENDER_METAL            (Wanted: ON): OFF
[cmake] --   SDL_RENDER_VULKAN           (Wanted: OFF): OFF
[cmake] --   SDL_ROCKCHIP                (Wanted: OFF): OFF
[cmake] --   SDL_RPATH                   (Wanted: OFF): OFF
[cmake] --   SDL_RPI                     (Wanted: OFF): OFF
[cmake] --   SDL_SNDIO                   (Wanted: OFF): OFF
[cmake] --   SDL_SNDIO_SHARED            (Wanted: OFF): OFF
[cmake] --   SDL_SSE                     (Wanted: ON): ON
[cmake] --   SDL_SSE2                    (Wanted: ON): ON
[cmake] --   SDL_SSE3                    (Wanted: ON): ON
[cmake] --   SDL_SSE4_1                  (Wanted: ON): ON
[cmake] --   SDL_SSE4_2                  (Wanted: ON): ON
[cmake] --   SDL_SYSTEM_ICONV            (Wanted: OFF): OFF
[cmake] --   SDL_TESTS                   (Wanted: OFF): OFF
[cmake] --   SDL_TESTS_LINK_SHARED       (Wanted: OFF): OFF
[cmake] --   SDL_VIRTUAL_JOYSTICK        (Wanted: OFF): OFF
[cmake] --   SDL_VIVANTE                 (Wanted: OFF): OFF
[cmake] --   SDL_VULKAN                  (Wanted: OFF): OFF
[cmake] --   SDL_WASAPI                  (Wanted: OFF): OFF
[cmake] --   SDL_WAYLAND                 (Wanted: OFF): OFF
[cmake] --   SDL_WAYLAND_LIBDECOR        (Wanted: OFF): OFF
[cmake] --   SDL_WAYLAND_LIBDECOR_SHARED (Wanted: OFF): OFF
[cmake] --   SDL_WAYLAND_SHARED          (Wanted: OFF): OFF
[cmake] --   SDL_X11                     (Wanted: OFF): OFF
[cmake] --   SDL_X11_SHARED              (Wanted: OFF): OFF
[cmake] --   SDL_X11_XCURSOR             (Wanted: OFF): OFF
[cmake] --   SDL_X11_XDBE                (Wanted: OFF): OFF
[cmake] --   SDL_X11_XFIXES              (Wanted: OFF): OFF
[cmake] --   SDL_X11_XINPUT              (Wanted: OFF): OFF
[cmake] --   SDL_X11_XRANDR              (Wanted: OFF): OFF
[cmake] --   SDL_X11_XSCRNSAVER          (Wanted: OFF): OFF
[cmake] --   SDL_X11_XSHAPE              (Wanted: OFF): OFF
[cmake] --   SDL_XINPUT                  (Wanted: ON): OFF

**Comment by sezero** [comment]
> > @sandsc: please confirm that current git main branch behaves in your environment
> 
> after delete cache and reconfigure cmake, issue still exists.
> ![image](https://private-user-images.githubusercontent.com/1673854/377280859-bf7ae5e0-9df8-440d-b023-9c2f4d02899b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMzAyMTcsIm5iZiI6MTcyOTEyOTkxNywicGF0aCI6Ii8xNjczODU0LzM3NzI4MDg1OS1iZjdhZTVlMC05ZGY4LTQ0MGQtYjAyMy05YzJmNGQwMjg5OWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTdUMDE1MTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzUwZDQ3M2Q1YzNkZTc2NTgwNTBjMmY4ODFmNWVjOGQ0YWViZmRkYzRkM2EzMjUyYjMxY2U4YjVjYjRjYTdmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.HFb2wVsoT6-JGb1YQnzXAM8yUeoSJdUiplp7hWaIbbs)

We are _not_ detecting gethostname for windows in cmake in current git. Did you update your SDL git tree?  Are you configuring SDL as part of some other project where you detect `gethostname` and set `HAVE_GETHOSTNAME` by any chance and that is somehow leaking into SDL's configuration??

**Comment by sezero** [comment]
Plus, we have no business at all with gethostbyname and gethostbyaddr, either.

**Comment by sandsc** [comment]
I debugged cmakelists.txt, just before generating SDL_build_config.h, found that variable `HAVE_GETHOSTNAME` is true, I'm using sdl by add_subdirectory, and like you said, it's possible that other projects are setting this variable, and I'll keep looking for this issue.
![image](https://github.com/user-attachments/assets/51282947-63c7-425c-a35d-49704f9f0df8)

**Comment by sandsc** [comment]
Found the reason, my project uses grpc, a third-party library of grpc ***cares*** set this variable.
![image](https://github.com/user-attachments/assets/0d1ee364-b9a4-418e-b5b1-308604de03ee)
I'm wondering if there's a good way to avoid this conflict？

**Comment by madebr** [comment]
Is https://github.com/libsdl-org/SDL/issues/11228#issuecomment-2417428024 still relevant?
[On Windows `gethostname` is provided by `winsock.h`](https://learn.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-gethostname).

**Comment by sandsc** [comment]
> Is [#11228 (comment)](https://github.com/libsdl-org/SDL/issues/11228#issuecomment-2417428024) still relevant? [On Windows `gethostname` is provided by `winsock.h`](https://learn.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-gethostname).

I unset HAVE_HOSTNAME before add sdl by subdirectory, But unfortunately, the `HAVE_HOSTNAME ` variable is still True, I think maybe this comment is the way to solve the problem. 

> I think the `<unistd.h>` include should be protected with a `#ifdef HAVE_UNISTD_H` macro, or `#if !(defined(SDL_PLATFORM_WIN32) || defined(SDL_PLATFORM_GDK))`.

this method sounds more reasonable, after all unistd.h is the name of the [header file](https://en.wikipedia.org/wiki/Header_file) that provides access to the [POSIX](https://en.wikipedia.org/wiki/POSIX) [operating system](https://en.wikipedia.org/wiki/Operating_system) [API](https://en.wikipedia.org/wiki/Application_programming_interface)
it should not only protected by HAVE_HOSTNAME.

**Comment by sandsc** [comment]
Now i got new problem, if projected `<unistd.h>` with `#ifdef HAVE_UNISTD_H`, HAVE_GETHOSTNAME  remains true, it compiles ok. but got link error.
> SDL3-static.lib(SDL_utils.obj) : error LNK2001: unresolved external symbol gethostname
:frowning_face:

**Comment by sezero** [comment]
We aren't using gethostname on windows, possibly because we don't want
to deal with winsock initialization (yes, @slouken / @icculus?) All we can
do here in SDL would be this:

```diff
diff --git a/src/SDL_utils.c b/src/SDL_utils.c
--- a/src/SDL_utils.c
+++ b/src/SDL_utils.c
@@ -20,7 +20,7 @@
 */
 #include "SDL_internal.h"
 
-#ifdef HAVE_GETHOSTNAME
+#if defined(HAVE_GETHOSTNAME) && !defined(SDL_PLATFORM_WINDOWS)
 #include <unistd.h>
 #endif
 
@@ -299,7 +299,7 @@ int SDL_URIToLocal(const char *src, char *dst)
             const size_t src_len = hostname_end - (src + 1);
             size_t hostname_len;
 
-#ifdef HAVE_GETHOSTNAME
+#if defined(HAVE_GETHOSTNAME) && !defined(SDL_PLATFORM_WINDOWS)
             char hostname[257];
             if (gethostname(hostname, 255) == 0) {
                 hostname[256] = '\0';
```

Apply this change and please re-test. If you still have linkage errors
after this, then you should link your own program to ws2_32.lib in order
to satisfy socket library requirements which are from grpc / c-ares.

Waiting for your response.

**Comment by sezero** [comment]
Well, I went ahead and applied the patch above as 4612db21a3450a5c2a0353558692dd32ccd3a794: test current git, please. Waiting for your response before closing this.

**Comment by sandsc** [comment]
Everything is ok now, thanks for the nice work!
