### ISSUE TITLE
Steam Deck gamepad is not picked up in desktop mode starting with SDL 2.30.9

### ISSUE THREAD

**Issue by streetpea** [libsdl-org/SDL#11861]
If you go into desktop mode on Steam Deck and switch into controller mode (hold the options button using the default desktop layout) the Steam Deck controller is not recognized using SDL 2.30.9+. This means I can't use the Steam Deck controller in games launched via base desktop mode. Prior to 2.30.9 the controller is recognized in desktop mode. If I launch the game via Steam in desktop mode, the controller works as expected. Looking at the release notes I see the note: `Fixed the Steam Virtual Gamepad from showing up when games aren't running under Steam` which seems like the most likely culprit as before (SDL 2.30.8-) it came up as a Steam Virtual gamepad in desktop mode. 

Note: Steam is running in the background to supply the controller config but the game isn't launched via Steam when this is happening.

**Comment by slouken** [comment]
This is fixed in the latest release!

**Comment by streetpea** [comment]
@slouken I seem to still have the issue with SDL 2.32.0 in desktop mode on Steam Deck

**Comment by streetpea** [comment]
@slouken I should add I tested this on SDL3 using sdl2-compat and the same problem exists there.
