### ISSUE TITLE
SDL3 renderer, flickering between previous and latest output buffer

### ISSUE THREAD

**Issue by LiquidityC** [libsdl-org/SDL#12432]
Not really sure how I should phrase this but I have an issue with the SDL renderer api where the output will flicker between the latest and previous render buffers. I consistently see this glitch on one of my laptops with the opengl backend (wayland), a rather new thinkpad with Intel Arc graphics but not on my other laptop with builtin intel graphics (also wayland).

A player is experiencing the same behavior on windows with the Direct3d11 renderer backend. Thankfully this player has been helping out and recorded some video of gameplay: https://www.youtube.com/watch?v=zCcPGmdH9nQ

At first I thought this was a driver issue since I'd only seen it on my own computer but now with the same thing happening on a different OS with a different driver I'm not so sure. Perhaps I've missed something when shifting from SDL2 to SDL3 even?

Thankful for any help explaining or clarifying this.

I'm tracking the issue in my repo here: https://github.com/Oliveshark/breakhack/issues/92, most likely no additional info. Just adding it for tracking.

**Comment by slouken** [comment]
Are you fully clearing and then drawing every frame? Does it happen with the SDL test programs?

**Comment by madebr** [comment]
On Linux, I can reproduce flickering in the following configurations:
- SDL_VIDEO_DRIVER=wayland SDL_RENDER_DRIVER=opengl: flickering as in youtube video you shared
- SDL_VIDEO_DRIVER=wayland SDL_RENDER_DRIVER=vulkan: flickering as in youtube video you shared + when in-game the menu "flickers in" (frames of the menu appear)
- SDL_VIDEO_DRIVER=x11 SDL_RENDER_DRIVER=vulkan: slight flickering only in the main menu

I don't see an issue with the software and gpu render driver.

**Comment by LiquidityC** [comment]
I clear and draw every frame. On my laptop it only happens when the game is in full screen. It's fine in windowed mode.

**Comment by slouken** [comment]
Does it happen with the SDL test programs?

**Comment by LiquidityC** [comment]
No. Not on the ones I've tried so far.

**Comment by LiquidityC** [comment]
Ok. I figured out the causing combo. It's viewports with moving parts that seems to be needed to reproduce. With the following patch applied to the viewport example I get the glitchy behavior.

```patch
diff --git a/examples/renderer/14-viewport/viewport.c b/examples/renderer/14-viewport/viewport.c
index 0a6c01515..8b3d8e091 100644
--- a/examples/renderer/14-viewport/viewport.c
+++ b/examples/renderer/14-viewport/viewport.c
@@ -78,6 +78,8 @@ SDL_AppResult SDL_AppEvent(void *appstate, SDL_Event *event)
 /* This function runs once per frame, and is the heart of the program. */
 SDL_AppResult SDL_AppIterate(void *appstate)
 {
+    static double angle = 0.0;
+
     SDL_FRect dst_rect = { 0, 0, (float) texture_width, (float) texture_height };
     SDL_Rect viewport;
 
@@ -104,6 +106,11 @@ SDL_AppResult SDL_AppIterate(void *appstate)
     viewport.h = WINDOW_HEIGHT / 2;
     SDL_SetRenderViewport(renderer, &viewport);
     SDL_RenderTexture(renderer, texture, NULL, &dst_rect);
+    SDL_FPoint point = {12, 12};
+    SDL_RenderTextureRotated(renderer, texture, NULL, &dst_rect, angle++, &point, SDL_FLIP_NONE);
+    if (angle > 360) {
+        angle = 0;
+    }
 
     /* bottom 20% of the window. Note it clips the width! */
     viewport.x = 0;
```

**Comment by madebr** [comment]
I was about to say that I can reduce the flickering (on wayland/vulkan) a lot (only some slight flickering the top left corner) by applying the following patch to breakhack that does not do `SDL_RenderPresent` when the render target is a texture.
```patch
-- a/src/roommatrix.c
+++ b/src/roommatrix.c
@@ -281,7 +281,7 @@ roommatrix_build_lightmap(RoomMatrix *matrix, Camera *camera)
                        SDL_RenderPoint(camera->renderer, (float) i, (float) j);
                }
        }
-       SDL_RenderPresent(camera->renderer);
+       //SDL_RenderPresent(camera->renderer);
        SDL_SetRenderTarget(camera->renderer, NULL);
 }
 
```

**Comment by LiquidityC** [comment]
Is **SDL_RenderPresent** not needed when rendering to textures? I wasn't aware of that. *(I just looked at the SDL3 docs and saw that this is mentioned now. Brilliant work with the docs for SDL3 by the way.)*

I can add to this and say that the problem can be made worse or better by tweaking things like vsync and frame rate. I have multiple displays and the problem will be worse or better depending on which one the game is on. I think the fact that some of the displays are DisplayLink and some are not has an effect here though.

Nothing completely removes the issue though. It's just better or worse.

**Comment by slouken** [comment]
Oh, yes, SDL_RenderPresent() should only be called once per frame, or ... you'll get flickering on some environments. :)

**Comment by madebr** [comment]
About the viewport, run with the `SDL_RENDER_VSYNC=1` environment variable. You're drawing too fast.

**Comment by slouken** [comment]
Also, test with the latest SDL code, we fixed a bug with resizing and renderers.

**Comment by LiquidityC** [comment]
@madebr Removing the bad call to SDL_RendererPresent fixed the issue. The graphical glitch in the top right was a bug (small version of the lightmap being rendered).

I'm happy to announce that this was all me then. Thanks for the assist.

**Comment by madebr** [comment]
Great to hear that!

But I think there is perhaps a small (documentation) bug remaining on the [wiki](https://wiki.libsdl.org/SDL3/SDL_RenderPresent):

> there is no need to call [SDL_RenderPresent](https://wiki.libsdl.org/SDL3/SDL_RenderPresent) after drawing needed objects to a texture,`

Should we make `SDL_RenderPresent` a nop when targeting a texture? Or should we update the documentation and change "is no need" to "you may not" (or something similar to discourage people doing this.

**Comment by slouken** [comment]
> Great to hear that!
> 
> But I think there is perhaps a small (documentation) bug remaining on the [wiki](https://wiki.libsdl.org/SDL3/SDL_RenderPresent):
> 
> > there is no need to call [SDL_RenderPresent](https://wiki.libsdl.org/SDL3/SDL_RenderPresent) after drawing needed objects to a texture,`
> 
> Should we make `SDL_RenderPresent` a nop when targeting a texture? Or should we update the documentation and change "is no need" to "you may not" (or something similar to discourage people doing this.
> 
> (A few weeks ago, I was also bit by this behavior while looking into somebody's SDL3 issue)

I think we should make it a no-op to present with a render target active. This is especially important now that logical presentation applies to render targets, someone might naturally assume that presenting on render targets is a thing. We're about to ship 3.2.6, but we should make that change shortly afterwards.

**Comment by icculus** [comment]
I feel like we changed this at some point because people forget to set the render target back before presenting.

**Comment by slouken** [comment]
> I feel like we changed this at some point because people forget to set the render target back before presenting.

You might be right...

**Comment by LiquidityC** [comment]
My 2c. Forgetting to set the render target back is a very big obvious visual break where you will instantly notice that you broke something. 

In the current scenario my mistake flew under the radar for weeks because my laptop didn't present the bug.
