### ISSUE TITLE
SDL3： On Windows 11, when using SDL3 to create a window on a Qt handle, keyboard events cannot be captured.

### ISSUE THREAD

**Issue by osenberg-x** [libsdl-org/SDL#12641]
A QWidget contains a child widget (QWidget). The handle of this child widget is passed to SDL3, and after SDL3 creates a window, it can only capture mouse events but not keyboard or other peripheral device events. What are the possible reasons?

**Comment by RobotLeopard86** [comment]
**Warning: I AM NOT AN SDL CONTRIBUTOR!! I was just screwing around, so take everything I say with a huge grain of salt.** 

I had this issue a bit ago; I fixed it by calling `QWindow::requestActivate`, and that got the events captured. It was still capturing keyboard input even when not focused then, so I had to implement a separate system to detect when the window could be considered "unfocused" by the user, such as other elements having focus and in that case setting a flag to ignore events. A bit convoluted, I know; I wasn't messing around with other focusable UI elements at the time (or if I was, I don't remember), so this all might be unnecessary. Either way, hope this helps!

**Comment by osenberg-x** [comment]
> **Warning: I AM NOT AN SDL CONTRIBUTOR!! I was just screwing around, so take everything I say with a huge grain of salt.**
> 
> I had this issue a bit ago; I fixed it by calling `QWindow::requestActivate`, and that got the events captured. It was still capturing keyboard input even when not focused then, so I had to implement a separate system to detect when the window could be considered "unfocused" by the user, such as other elements having focus and in that case setting a flag to ignore events. A bit convoluted, I know; I wasn't messing around with other focusable UI elements at the time (or if I was, I don't remember), so this all might be unnecessary. Either way, hope this helps!

Thank you for your reply. I tried the method you mentioned, but it didn't solve my problem. Keyboard events still cannot be captured on the SDL side.

`  explicit StreamVideo(QWidget *parent = nullptr) : QWidget{parent} {
    setWindowFlags(Qt::Widget | Qt::FramelessWindowHint);

    QWidget *mainWindow = QApplication::activeWindow();
    QWindow *windowHandle = mainWindow->windowHandle();
    windowHandle->requestActivate();
  }`

**Comment by RobotLeopard86** [comment]
Sorry that didn't help! That was from a little while ago, and I have lost the source. I guess this probably won't help anyway, since I remember that I was doing this with a `WindowContainer` in QML, not attaching SDL to a `QMainWindow`. Sorry for wasting your time! Like I said, I'm not an SDL contributor, but I do know some about window interop and QPA. If the source is on your GitHub or you can put it there, maybe I can help? My guess would be that it's a lifecycle issue. SDL and Qt both want to own the main thread, so it might help to know how you're processing events. The way I thought to integrate them was something like this:
```cpp
QApplication theApp(argc, argv);
//Other init code...
while(running) {
    SDL_Event e;
    while(SDL_PollEvent(&e)) {
        //Event processing...
    }
    theApp.processEvents();
    //Other loop code...
}
//Shutdown code...
```
I would guess that if you are using `QApplication::exec` then maybe it's a threading issue. Hope I can help in some way!

**Comment by RobotLeopard86** [comment]
That sounds like that might be the problem. From my experience, SDL expects the provider of an `HWND` to handle window updates on it's own. I believe this is because the window is not using SDL's `WNDCLASS` which allows SDL to receive events. If you're not calling `QApplication::processEvents` or similar methods, I don't think SDL will actually see anything. I know this is not Windows-related, but `docs/README-wayland.md` has an example of using a Qt-created Window on Wayland (Linux), and you'll notice it does this for window updating:
```cpp
while (SDL_PollEvent(&e)) {
    if (e.type == SDL_EVENT_KEY_DOWN && e.key.key == SDLK_ESCAPE) {
        done = 1;
    }
}

qtApp.processEvents();
```
Just make sure to do that on the main thread. Hope this helps!

**Comment by osenberg-x** [comment]
> [@osenberg-x](https://github.com/osenberg-x) Has this helped?

Sorry for not replying to you earlier. I used a different method to solve this problem. Instead of passing the handle of a Qt component to SDL3, I passed the handle of the entire Qt window to SDL3. Then, every time the resolution changes, SDL rebuilds the window on the handle to solve the issue of rendering overlapping the menu bar.

**Comment by RobotLeopard86** [comment]
That's great. I hope this project goes well for you. Not sure how to let the SDL people now that they can close this issue (assuming everything works on your end). If you did want to work in a component, I would suggest `QWindowContainer` but I've had some issues in the past with that. Again, hope your project goes well!
