### ISSUE TITLE
Windows 10: specifying SDL_WINDOW_FULLSCREEN | SDL_WINDOW_BORDERLESS and creating a desktop sized window shows border briefly

### ISSUE THREAD

**Issue by danginsburg** [libsdl-org/SDL#13695]
This problem can reproduced in SDL3 main (f44a98729c3ac66056f39ee690a44a2c7440274b) on Windows 10 with:

```
testwm.exe --fullscreen-desktop --noframe --logical 1920x1080 --geometry 2560x1440
```

For a brief moment you will see the window border draw as in the screenshot.

<img width="1859" height="819" alt="Image" src="https://github.com/user-attachments/assets/e88dad4b-8248-44b9-9274-6d1abb8cb3f0" />

**Comment by Kontrabant** [comment]
This seems to only occur with the particular combination of the STYLE_BORDERLESS_WINDOWED flags and the initial window size exactly matching the desktop dimensions. The solution is to always set STYLE_BORDERLESS when showing if the window will immediately become fullscreen.

**Comment by Kontrabant** [comment]
Should be fixed now.

**Comment by danginsburg** [comment]
I'm actually still seeing the issue after building with your fix running:
```
testwm.exe --fullscreen-desktop --noframe --logical 1920x1080 --geometry 2560x1440
```

**Comment by danginsburg** [comment]
This additional change fixes it for me, but is probably not the proper fix:

```
diff --git a/src/video/windows/SDL_windowswindow.c b/src/video/windows/SDL_windowswindow.c
index 147f6e8f3..4d53419c6 100644
--- a/src/video/windows/SDL_windowswindow.c
+++ b/src/video/windows/SDL_windowswindow.c
@@ -252,7 +252,7 @@ static bool WIN_AdjustWindowRectWithStyle(SDL_Window *window, DWORD style, DWORD
     /* borderless windows will have WM_NCCALCSIZE return 0 for the non-client area. When this happens, it looks like windows will send a resize message
        expanding the window client area to the previous window + chrome size, so shouldn't need to adjust the window size for the set styles.
      */
-    if (!(window->flags & SDL_WINDOW_BORDERLESS) && !SDL_WINDOW_IS_POPUP(window)) {
+    if (!SDL_WINDOW_IS_POPUP(window)) {
 #if defined(SDL_PLATFORM_XBOXONE) || defined(SDL_PLATFORM_XBOXSERIES)
         AdjustWindowRectEx(&rect, style, menu, 0);
 #else

```

**Comment by Kontrabant** [comment]
Ah, I think the root issue was in the WM_NCCALCSIZE handler: the window flags are used to determine if any work is required, however, they were retrieved with SDL_GetWindowFlags(), which also includes pending flags set during the creation/show phase. The message wasn't being handled, because the fullscreen flag was set as pending, making the window appear to be fullscreen when it wasn't yet.

Please try https://github.com/Kontrabant/SDL/tree/win32_calc_size

**Comment by danginsburg** [comment]
> Please try https://github.com/Kontrabant/SDL/tree/win32_calc_size

I gave this a try and am happy to report it fixes the issue.  Thanks!

**Comment by Kontrabant** [comment]
You’re welcome!

**Comment by slouken** [comment]
@Kontrabant, can you cherry-pick these changes to 3.2.x if appropriate?

**Comment by Kontrabant** [comment]
Yes, had to run out for a moment, but will do so shortly.

**Comment by Kontrabant** [comment]
Cherry-picking done, sorry for the delay.

**Comment by slouken** [comment]
Thanks!
