### ISSUE TITLE
Calling `SDL_WarpMouseInWindow` immediatelly after turning off relative mode produces unexpected results

### ISSUE THREAD

**Issue by Susko3** [libsdl-org/SDL#4339]
If the mouse is moving, and you disable relative mode and then warp the cursor, sometimes the cursor will not warp.

Code used to reproduce the issue:
```c++
#include <SDL.h>
#include <SDL_hints.h>

int main(int argc, char** args)
{
    SDL_Init(SDL_INIT_EVENTS);
    SDL_Window* win = SDL_CreateWindow("test window", 100, 100, 1200, 500, SDL_WINDOW_RESIZABLE);
    SDL_SetHint(SDL_HINT_EVENT_LOGGING, "2");

    bool loop = true;
    bool relative = false;
    SDL_SetRelativeMouseMode(SDL_bool::SDL_FALSE);

    while (loop)
    {
        SDL_Event e;
        while (SDL_PollEvent(&e) > 0)
        {
            if (e.type == SDL_EventType::SDL_KEYDOWN)
            {
                SDL_Keysym key = e.key.keysym;
                if (key.sym == SDLK_b)
                {
                    relative = !relative;
                    SDL_SetRelativeMouseMode(relative ? SDL_bool::SDL_TRUE : SDL_bool::SDL_FALSE);
                    if (!relative)
                    {
                        SDL_WarpMouseInWindow(win, 1000, 250);
                        SDL_Log("warp");
                    }
                    else
                        SDL_Log("toggle");
                }

                if (key.sym == SDLK_ESCAPE)
                    loop = false;
            }
        }
    }
    return 0;
}
```

https://user-images.githubusercontent.com/16479013/116155093-ed137c00-a6e9-11eb-9330-43164f258d87.mp4

How to reproduce:

1. Press B once to enable relative mode (the OS cursor will dissapear)
2. Start moving your mouse (I do it in a circle on the left side of the window, so it's easier to track)
3. Press B to disable relative mode and warp the cursor
4. The cursor will appear on the screen, but the location of the cursor is not predictable

The cursor is expected to be at the location that `SDL_WarpMouseInWindow` specified (on the right side of the window, with my example code). Sometimes the cursor will appear here as expected.
But if the bug occurs, the cursor will not warp, and will appear on the location of the last `SDL_MOUSEMOTION` event (on the left side in the video).

If you don't move your mouse, the cursor will always appear in the location specified by `SDL_WarpMouseInWindow`.

There is a slight difference between the latest `main` and `2.0.14`: On `2.0.14` it's the same as `main`, but the cursor can also appear in the middle of the window.

Seems to happen much more frequently when mouse report rate is set to 1000 Hz. But I managed to reproduce it with 125 Hz, as seen in the logs below:

Normal logs:
```
INFO: SDL EVENT: SDL_MOUSEMOTION (timestamp=8916 windowid=1 which=0 state=0 x=83 y=116 xrel=29 yrel=-10)
INFO: SDL EVENT: SDL_MOUSEMOTION (timestamp=8923 windowid=1 which=0 state=0 x=122 y=104 xrel=39 yrel=-12)
INFO: SDL EVENT: SDL_MOUSEMOTION (timestamp=8932 windowid=1 which=0 state=0 x=167 y=94 xrel=45 yrel=-10)
INFO: SDL EVENT: SDL_KEYDOWN (timestamp=8936 windowid=1 state=pressed repeat=false scancode=5 keycode=98 mod=0)
INFO: SDL EVENT: SDL_TEXTINPUT (timestamp=8936 windowid=1 text='b')
INFO: warp
INFO: SDL EVENT: SDL_MOUSEMOTION (timestamp=8939 windowid=1 which=0 state=0 x=1035 y=243 xrel=868 yrel=149)
INFO: SDL EVENT: SDL_MOUSEMOTION (timestamp=8947 windowid=1 which=0 state=0 x=1050 y=242 xrel=15 yrel=-1)
INFO: SDL EVENT: SDL_MOUSEMOTION (timestamp=8955 windowid=1 which=0 state=0 x=1048 y=242 xrel=-2 yrel=0)
INFO: SDL EVENT: SDL_MOUSEMOTION (timestamp=8963 windowid=1 which=0 state=0 x=1034 y=248 xrel=-14 yrel=6)
```

Logs when the cursor doesn't warp:
```
INFO: SDL EVENT: SDL_MOUSEMOTION (timestamp=10211 windowid=1 which=0 state=0 x=182 y=259 xrel=-3 yrel=2)
INFO: SDL EVENT: SDL_MOUSEMOTION (timestamp=10219 windowid=1 which=0 state=0 x=187 y=258 xrel=5 yrel=-1)
INFO: SDL EVENT: SDL_MOUSEMOTION (timestamp=10227 windowid=1 which=0 state=0 x=201 y=253 xrel=14 yrel=-5)
INFO: SDL EVENT: SDL_KEYDOWN (timestamp=10235 windowid=1 state=pressed repeat=false scancode=5 keycode=98 mod=0)
INFO: SDL EVENT: SDL_TEXTINPUT (timestamp=10235 windowid=1 text='b')
INFO: warp
INFO: SDL EVENT: SDL_MOUSEMOTION (timestamp=10236 windowid=1 which=0 state=0 x=224 y=246 xrel=23 yrel=-7)
INFO: SDL EVENT: SDL_MOUSEMOTION (timestamp=10243 windowid=1 which=0 state=0 x=248 y=242 xrel=24 yrel=-4)
INFO: SDL EVENT: SDL_MOUSEMOTION (timestamp=10252 windowid=1 which=0 state=0 x=265 y=239 xrel=17 yrel=-3)
INFO: SDL EVENT: SDL_MOUSEMOTION (timestamp=10259 windowid=1 which=0 state=0 x=267 y=239 xrel=2 yrel=0)
```

**Comment by Susko3** [comment]
Looks to be similar to https://github.com/libsdl-org/SDL/issues/4165. The linked PR (https://github.com/libsdl-org/SDL/pull/4266) does not fix my issue.

**Comment by slouken** [comment]
I was able to reproduce this with an 8K Razer Viper mouse.
As far as I can tell this is a bug with Windows. When relative mode is turned off, the mouse is warped back to where it was before relative mode was turned on. Your code immediately follows that with another call to set the mouse position. Both calls succeed, but occasionally, if the timing is close enough, the second one (in your code) is ignored.

**Comment by Susko3** [comment]
FYI, I've been using this code (slightly modified from https://github.com/libsdl-org/SDL/issues/4165#issuecomment-938176267)

```c
#include "SDL.h"

int
main(int argc, char* argv[])
{
    int w = 1024;
    int h = 768;
    SDL_Window* window;
    SDL_Renderer* renderer;
    SDL_Surface* image;
    SDL_Texture* sprite;
    SDL_Rect rect;
    SDL_bool done = SDL_FALSE;
    SDL_bool was_relative = SDL_FALSE;
    SDL_bool relative = SDL_FALSE;

    SDL_SetHint(SDL_HINT_EVENT_LOGGING, "2");

    if (SDL_CreateWindowAndRenderer(w, h, SDL_WINDOW_SHOWN, &window, &renderer) < 0) {
        return 1;
    }

    image = SDL_LoadBMP("icon.bmp");
    if (!image) {
        return 2;
    }
    rect.w = image->w;
    rect.h = image->h;

    sprite = SDL_CreateTextureFromSurface(renderer, image);
    if (!sprite) {
        return 3;
    }
    SDL_FreeSurface(image);

    while (!done) {
        SDL_Event e;

        while (SDL_PollEvent(&e) == 1) {
            if (e.type == SDL_QUIT) {
                done = 1;
            }
            if (e.type == SDL_KEYDOWN && e.key.keysym.sym == SDLK_ESCAPE) {
                done = 1;
            }
        }

        SDL_GetMouseState(&rect.x, &rect.y);

        if (rect.x == 0 || rect.x == (w - 1) ||
            rect.y == 0 || rect.y == (h - 1)) {
            relative = SDL_FALSE;
        }
        else {
            relative = SDL_TRUE;
        }
        if (relative != was_relative) {
            SDL_WarpMouseInWindow(window, rect.x, rect.y);
            SDL_SetRelativeMouseMode(relative);
            if (!relative) {
                SDL_WarpMouseInWindow(window, rect.x, rect.y);
                SDL_FlushEvent(SDL_MOUSEMOTION);
            }
            was_relative = relative;
        }

        SDL_RenderClear(renderer);
        rect.x -= rect.w / 2;
        rect.y -= rect.h / 2;
        SDL_RenderCopy(renderer, sprite, NULL, &rect);
        SDL_RenderPresent(renderer);
    }
    SDL_Quit();
    return 0;
}
```

**Comment by mjdave** [comment]
Interesting thanks I wasn't aware of that hint.

However I've now tried both of these, and get the same issue. I see no change if I call SDL_WarpMouseInWindow before SDL_SetRelativeMouseMode (as well as after).

If I use the warp hint, I do see very different acceleration curves, but I still see the cursor jump in the same way as before on the switch out. Logging the mouse position as above also still shows that the position is not being reset to the center when in relative mode. It still moves freely around, constrained within the window bounds, and the cursor still shows up at the logged location if there is constant mouse movement on the switch.

**Comment by 0x1F9F1** [comment]
This is hopefully fixed by #4831. Any testing would be appreciated.

**Comment by slouken** [comment]
Please retest using the latest SDL snapshot at commit https://github.com/libsdl-org/SDL/commit/a1fabca162091b50d6f7dd71879d028319e09d80:
http://www.libsdl.org/tmp/SDL-2.0.zip

Thanks!

**Comment by Susko3** [comment]
Unfortunately, this is still a problem. Even on the latest `main` branch.
Especially when one's mouse is set to 1000 Hz, where the unexpected jump is far more common.

With the test code, when the cursor leaves the window (and relative mode is therefore disabled) it will sometimes jump to the center of the window.

More precisely, it will jump to where the OS cursor currently is, which is the center of the window because it was [previously clipped to there](https://github.com/libsdl-org/SDL/blob/70c8d20a46e6988f199ff8c1976f3cb49382a999/src/video/windows/SDL_windowswindow.c#L1012-L1027).

The jump happens precisely because Windows sometimes ignores the `SetCursorPos()` calls here, and doesn't move the cursor:
(This is probably a bug in Windows, and there probably isn't a quick fix for it. The only thing we can do is call `SetCursorPos()` multiple times and pray that one goes trough, but this is prone to failure.)

https://github.com/libsdl-org/SDL/blob/881f747d5c8026a6d4f456db60cf11e67ddd1366/src/video/windows/SDL_windowsmouse.c#L251-L256

Probably the only real way to fix this issue is to keep the SDL and OS cursor in sync, so when relative mode is disabled (and `SetCursorPos()` fails), the OS and SDL cursors are close enough, so the jump will be unnoticeable.

So I suggest we go back to clipping the cursor to the whole window, as done here: [PR#4266](https://github.com/libsdl-org/SDL/pull/4266/files#diff-f2ae5c36a8afc0a9a343a6664ab306da2963213e180af8cd97b12397dcbb9ae7R983-R988).
With that PR, the two cursors usually stay in sync, with a few pixel difference at most.

#4266 is merged, but that change was reverted [here](https://github.com/libsdl-org/SDL/commit/a1fabca162091b50d6f7dd71879d028319e09d80?diff=unified#diff-f2ae5c36a8afc0a9a343a6664ab306da2963213e180af8cd97b12397dcbb9ae7L977-R1003) without any comment or reasoning.

If there is a specific reason for clipping the cursor to a 2x2 rect, we can settle on a hint that toggles the behavior between the two.

<details>
<summary>Latest test code (all of this was tested on latest `main` branch)</summary>

```c
#include "SDL.h"

SDL_Window* window;
SDL_Renderer* renderer;

void draw_cursor()
{
    SDL_Rect cursor_rect;

    SDL_GetMouseState(&cursor_rect.x, &cursor_rect.y);
    cursor_rect.w = 26;
    cursor_rect.h = 26;
    cursor_rect.x -= cursor_rect.w / 2;
    cursor_rect.y -= cursor_rect.h / 2;

    SDL_SetRenderDrawColor(renderer, 0, 0, 0, SDL_ALPHA_OPAQUE);
    SDL_RenderClear(renderer);
    SDL_SetRenderDrawColor(renderer, 255, 255, 0, SDL_ALPHA_OPAQUE);
    SDL_RenderFillRect(renderer, &cursor_rect);
    SDL_RenderPresent(renderer);
}

SDL_bool use_relative = SDL_FALSE;

void update_relative(int dx, int dy)
{
    int x, y, w, h;

    SDL_GetMouseState(&x, &y);
    SDL_GetWindowSize(window, &w, &h);

    x += dx;
    y += dy;

    // disable relative when outside of window.
    if (x < 0 || y < 0 || x >= w || y >= h) {
        use_relative = SDL_FALSE;
    }

    if (use_relative != SDL_GetRelativeMouseMode()) {
        SDL_SetRelativeMouseMode(use_relative);
    }
}

int main()
{
    SDL_Init(SDL_INIT_VIDEO);
    SDL_CreateWindowAndRenderer(1000, 700, SDL_WINDOW_SHOWN | SDL_WINDOW_RESIZABLE, &window, &renderer);
    //SDL_SetHint(SDL_HINT_EVENT_LOGGING, "2");

    SDL_bool main_loop = SDL_TRUE;
    while (main_loop) {
        SDL_Event e;
        while (SDL_PollEvent(&e) == 1) {
            switch (e.type)
            {
            case SDL_QUIT:
                main_loop = SDL_FALSE;
                break;

            case SDL_KEYDOWN:
                if (e.key.keysym.sym == SDLK_ESCAPE)
                    main_loop = SDL_FALSE;
                break;

            case SDL_MOUSEMOTION:
                if (SDL_GetRelativeMouseMode() == SDL_TRUE) {
                    update_relative(e.motion.xrel, e.motion.yrel);
                }
                break;

            case SDL_WINDOWEVENT:
                if (e.window.event == SDL_WINDOWEVENT_ENTER) {
                    use_relative = SDL_TRUE;
                    update_relative(0, 0);
                }
                break;
            }
        }
        draw_cursor();
    }
    SDL_Quit();
    return 0;
}
```

</details>
