### ISSUE TITLE
Running a compiled-from-source SDL2 under a regular GNOME 3 Wayland DE gives me "No message system available" for SDL_ShowSimpleMessageBox()

### ISSUE THREAD

**Issue by ell1e** [libsdl-org/SDL#4495]
Running a compiled-from-source SDL2 under a regular GNOME 3 Wayland DE on a Fedora 34 machine gives me "No message system available" for `SDL_ShowSimpleMessageBox()`. I just use a standard GNOME 3 desktop with a Wayland session, surely there should be ways to display a message box? Does SDL2 expect some obscure helper program to be around to do this, or what could be the issue?

Please note that due to https://github.com/libsdl-org/SDL/issues/3689 I had to compile with Wayland support disabled. But even then XWayland integration otherwise seems to work fine, so it seems odd to me this would get in the way of something as basic as a message box.

**Comment by flibitijibibo** [comment]
Sounds like no video system is being built at all... build instructions for Fedora 34 that work on my setups:

```
sudo dnf builddep SDL2
git clone git://github.com/libsdl-org/SDL.git
cd SDL
./configure && make
```

**Comment by ell1e** [comment]
@flibitijibibo I can launch the app fine, and draw things, not sure how that would work without a video system. It definitely only has an X11 one and no Wayland one due to above bug. Only message boxes do not work, otherwise graphics work fine.

**Comment by flibitijibibo** [comment]
This is probably the best place to step

https://github.com/libsdl-org/SDL/blob/main/src/video/SDL_video.c#L4142

**Comment by flibitijibibo** [comment]
Pretty sure this is fixed by https://github.com/libsdl-org/SDL/commit/98c983628726359ee2ccb9053b394fb0e04dbb8f

**Comment by slouken** [comment]
Actually that commit will show what the real error is, but it sounds like the messagebox still won't show up.

@ell1e, can you debug into it and see what's happening?

**Comment by slouken** [comment]
SDL 2.0 is now in maintenance mode, and all inactive issues are being closed. If this issue is impacting you, please feel free to reopen it with additional information.
