### ISSUE TITLE
SDL handling of directinput is prone to dropping inputs and losing state

### ISSUE THREAD

**Issue by Mattk50** [libsdl-org/SDL#4528]
This is based on this thread, problem once figured out is discussed in detail in the linked post but other than the last post it's just hunting down the problem without actually finding it: https://discourse.libsdl.org/t/sdl2-is-consistently-dropping-joystick-inputs/32191/7

I think there are two main changes that would alleviate this problem.

First, the directinput buffer needs to be bigger, much bigger. It should be set to be as big as the device can allow, 32 is too small. The program would need to be restructured a bit as you cant just set the buffer size in SDL too big or the compiler starts yelling at you for memory issues, maybe you can just keep using the smaller array and loop over all the events instead of trying to drain the entire directinput one all at once. But really this buffer is 32 and needs to be like 1000 to be safe, optimally even higher if you want complete security against hitches.

Second, the buffered input mode should still keep track of state. the main interface to SDL2 is event polling, so we on the other end of SDL don't easily have the option to compare state ourselves, therefore SDL2 should be handling this. When SDL2 notices that the directinput buffer is full, it should notice that events might have been dropped, and then do an extra step to compare the controller's state and additionally generate inputs for anything that's changed and hasn't already been picked up by an event. 

I consider this a pretty critical bug for any game that relies on directinput joysticks, and it seems like mouse ran into the same problem in the past and had this resolved by a huge directinput buffer size increase in SDL. Personally i wouldn't not play a game that had such a high chance of just randomly dropping a trigger pull or trigger release.

**Comment by slouken** [comment]
This should be fixed by https://github.com/libsdl-org/SDL/commit/d4ac6b5ed91cbdce856e4830a4311108e42791ba, thanks!

**Comment by Dorenix** [comment]
I am working on a project with version 2.26.2 and I still have this issue, button down and button up events are sometimes droped. I use DualShock 4. Any Ideas why that might be the case?
