### ISSUE TITLE
X11: Setting window to fullscreen fails with `RRScreenSize` reporting `BadMatch`

### ISSUE THREAD

**Issue by bdach** [libsdl-org/SDL#4561]
Hi,

On recent versions on SDL I am seeing failures to display a fullscreen window. Before I proceed, a few notes on my hardware setup (as it's possibly relevant):

* I am on a Ubuntu 16.04 system (`uname -a` says `4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`), with x11, running i3 as the window manager
* I have two physical monitors, one of which has a 2560x1080 resolution, and the other has a 1920x1080 resolution

Below is a minimal reproducer example that fails for me with current `main` (please forgive the haphazard error handling, I do not program C often if at all these days):

```c
#include <stdio.h>
#include <stdlib.h>
#include "../SDL/include/SDL.h"

int main(int argc, char **argv)
{
    if (SDL_Init(SDL_INIT_VIDEO) < 0)
    {
        printf("SDL failed to initialise with error %s\n", SDL_GetError());
        return EXIT_FAILURE;
    }

    SDL_Window *window = NULL;

    window = SDL_CreateWindow("test", 0, 0, 2560, 1080, SDL_WINDOW_SHOWN | SDL_WINDOW_FULLSCREEN);

    if (window == NULL)
    {
        printf("Window was not created: %s\n", SDL_GetError());
        return EXIT_FAILURE;
    }

    SDL_Renderer *renderer = SDL_CreateRenderer(window, -1, 0);

    SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
    SDL_RenderClear(renderer);
    SDL_RenderPresent(renderer);

    int quit = 0;

    SDL_Event e;

    while (!quit) {
        while (SDL_PollEvent(&e) != 0) {
            if (e.type == SDL_QUIT) {
                quit = 1;
            }
        }
    }

    return EXIT_SUCCESS;
}
```

This on my system fails with

```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  7 (RRSetScreenSize)
  Serial number of failed request:  256
  Current serial number in output stream:  257
```

I have managed to trace this back to https://github.com/libsdl-org/SDL/commit/16e3bfe807dfdd48b6833da4cd78e789a920e2ec; commenting out the call to `X11_XRRSetScreenSize` prevents the crash to desktop.

The reason why I stated that this is possibly related to my monitor configuration is that upon some digging and instrumenting the call above with some log statements I have managed to fish out the following:

```
INFO: DisplayWidth = 4480, DisplayWidthMM = 1518
INFO: DisplayHeight = 1080, DisplayHeightMM = 366
INFO: about to XRRSetScreenSize (display = 55c9cd09e0f0, window = 254, w = 2560, h = 1080, mmWidth = 867, mmHeight = 366)
```

Note that `DisplayWidth` and `DisplayHeight` say 4480x1080, so it's the *total* resolution of *both* my screens. `xrandr` reports: (somewhat truncated)

```
Screen 0: minimum 8 x 8, current 4480 x 1080, maximum 16384 x 16384
eDP-1-1 connected 1920x1080+2560+0 (normal left inverted right x axis y axis) 344mm x 194mm
HDMI-1-1 connected 2560x1080+0+0 (normal left inverted right x axis y axis) 673mm x 284mm
```

I am not sure where `xlib` got the 1518x366 measurements from, and since I do not routinely develop anything for x11 I have no idea what the proper API would be for fetching the single screen's size.

If I can provide any further information or test possible patches/PRs to resolve this please let me know.

**Comment by icculus** [comment]
We probably need to examine this or revert the mentioned changeset for 2.0.16.

**Comment by bdach** [comment]
I have poked around some more and have found another detail that may be obvious but I want to state it for the record at least.

If I change my reproducer example to show the window at 1920x1080, which is a mode that *both* my displays support, the error does not happen. In other words, a necessary condition for triggering this crash is to attempt creating a fullscreen window with a size that is not supported by all displays.

In fact, after stumbling upon what seems to be [randr documentation](https://cgit.freedesktop.org/xorg/proto/randrproto/tree/randrproto.txt), this is stated in plain language near the section on `RRSetScreenSize`:

> Sets the screen to the specified size. 'width' and 'height' must be 
> the range allowed by GetScreenSizeRanges, otherwise a Value
> results. All active monitors must be configured to display a
> subset of the specified size, else a Match error results.

So it seems that this call can never succeed if the size is not valid for all of the active monitors. I can't really find anything that would look like the *right* thing to call in this scenario and not break the original fix, however.

**Comment by icculus** [comment]
I've pushed a change to prevent the crash, but I don't have a configuration to reproduce this.  @bdach, I'd appreciate it if you could try the latest in revision control and see if your problem goes away there.

**Comment by bdach** [comment]
Thanks for the prompt response. I've made a quick and dirty attempt of trying out latest `main` and I have bad (?) news. d0effad itself does not fix the issue - the installed error handler never fires.

As I understand X has some degree of asynchronicity built into it, so mostly for the sake of experimentation I crudely instrumented the calls with logging and attempted delaying the restoration of the error handler to be at a later point, applying the following patch:

```diff
diff --git a/src/video/x11/SDL_x11modes.c b/src/video/x11/SDL_x11modes.c
index 7dab9ff5..7d100341 100644
--- a/src/video/x11/SDL_x11modes.c
+++ b/src/video/x11/SDL_x11modes.c
@@ -1001,6 +1001,7 @@ static int (*PreXRRSetScreenSizeErrorHandler)(Display *, XErrorEvent *) = NULL;
 static int
 SDL_XRRSetScreenSizeErrHandler(Display *d, XErrorEvent *e)
 {
+    SDL_Log("error handler fired with error code %d", e->error_code);
     return (e->error_code == BadMatch) ? 0 : PreXRRSetScreenSizeErrorHandler(d, e);
 }
 
@@ -1057,15 +1058,18 @@ X11_SetDisplayMode(_THIS, SDL_VideoDisplay * sdl_display, SDL_DisplayMode * mode
            for now we cheat and just catch the X11 error and carry on, which
            is likely to cause subtle issues but is better than outright
            crashing */
+        SDL_Log("this is where the error handler is set");
         PreXRRSetScreenSizeErrorHandler = X11_XSetErrorHandler(SDL_XRRSetScreenSizeErrHandler);
         X11_XRRSetScreenSize(display, RootWindow(display, data->screen), mode->w, mode->h, mm_width, mm_height);
-        X11_XSetErrorHandler(PreXRRSetScreenSizeErrorHandler);
+        SDL_Log("this is where the error handler *was* reset, initially");
 
         status = X11_XRRSetCrtcConfig (display, res, output_info->crtc, CurrentTime,
           crtc->x, crtc->y, modedata->xrandr_mode, crtc->rotation,
           &data->xrandr_output, 1);
 
 setCrtcError:
+        SDL_Log("this is where the error handler *is* reset now (which is at setCrtcError)");
+        X11_XSetErrorHandler(PreXRRSetScreenSizeErrorHandler);
         X11_XUngrabServer(display);
         X11_XRRFreeCrtcInfo(crtc);
         X11_XRRFreeOutputInfo(output_info);
```

and with that above change applied, my reproducer prints

```
INFO: this is where the error handler is set
INFO: this is where the error handler *was* reset, initially
INFO: error handler fired with error code 8
INFO: this is where the error handler *is* reset now (which is at setCrtcError)
INFO: this is where the error handler is set
INFO: this is where the error handler *was* reset, initially
INFO: error handler fired with error code 8
INFO: this is where the error handler *is* reset now (which is at setCrtcError)
INFO: this is where the error handler is set
INFO: this is where the error handler *was* reset, initially
INFO: error handler fired with error code 8
INFO: this is where the error handler *is* reset now (which is at setCrtcError)
```

and launches correctly, with the correct resolution.

Whether this is really safe or has any possible side effects, I couldn't really even attempt to guess, and the above is mostly a result of semi-blind experimentation...

**Comment by icculus** [comment]
We probably need an XSync() call in there (but I have to look at what XGrabServer does first).

**Comment by cgutman** [comment]
fwiw, I see the same issue running `testgl2 --fullscreen` under XWayland.

```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  7 (RRSetScreenSize)
  Serial number of failed request:  257
  Current serial number in output stream:  258
```

**Comment by icculus** [comment]
@bdach and @cgutman: try the latest in revision control and see if it actually catches the error without dying now. If this doesn't cut it, I'll get more aggressive and go with @bdach's approach.

**Comment by cgutman** [comment]
That fixes it for me, but I still feel like there must be something more deeply wrong with 16e3bfe807dfdd48b6833da4cd78e789a920e2ec to be causing issues in such varied configs like this.

**Comment by bdach** [comment]
I've tested 4c7825f (with both my reproducer in the OP, as well the original application that was using SDL in which I originally hit this issue), and the sync seems to have made the error handler work on my end as well :+1:

**Comment by icculus** [comment]
> That fixes it for me, but I still feel like there must be something more deeply wrong with 16e3bfe to be causing issues in such varied configs like this.

Agreed, but we're looking to ship 2.0.16, so this is a mitigation for now and we'll look more closely afterwards.

**Comment by slouken** [comment]
Moving this bug to 2.0.18 for further investigation.

@cgutman if you want to take a closer look, that would be great. We can't reproduce the issue here.

**Comment by sjnewbury** [comment]
Not sure which patch caused it, but I just get a black screen on fullscreen XWayland now when running under mutter/gnome-shell.  Weston breaks differently, and I also tried enlightenment, which gives a "BAD MATCH" error.

I'll try to bisect and find the culprit.

**Comment by sjnewbury** [comment]
I've discovered what's wrong with my setup, it *might* be a related bug.

I have had SDL_VIDEO_X11_XRANDR=0 set in my environment for many years since I didn't get along with the resolution switching back in the day.

Apparently, on my system, at least, fullscreen X11 through Xwayland results in the black screen as described with that variable set to "0", but works fine with it unset!

**Comment by icculus** [comment]
The fallback is probably XVidMode, which doesn't work in SDL2 in almost all cases.

(It was spared from removal because apparently it's the only thing that works with VNC.)

**Comment by icculus** [comment]
Going to close this, because my reading of this bug is that we fixed the issue but there's still things wrong with XVidMode, which we will be deleting outright in #1782.
