### ISSUE TITLE
[WAYLAND] Mouse cursor is sticky around the edges in Scummvm

### ISSUE THREAD

**Issue by vanfanel** [libsdl-org/SDL#4822]
Hi there,

I have noticed that when using the Wayland backend, the mouse in Scummvm is sticky around the edges. This means that, internally, the mouse coordinates are increased beyond the game area, which shouldn't happen.

It only happens on the Wayland backend: this behavior is not present on KMSDRM or X11.

Since you are pushing a lot of wayland work these days, I thought it could be a good time to open this issue.
I have zero knowledge on Wayland, so I can't research this myself.

**Comment by flibitijibibo** [comment]
Thankfully this is just a single function in the Wayland driver and it's what you would hope it would be:

https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandevents.c#L261

I wonder if it's something like DPI affecting this? In any case, printf'ing in here will probably tell you what you need to know.

**Comment by flibitijibibo** [comment]
Just did a check against GNOME/Plasma/sway and was able to confirm that this is exclusive to GNOME - @vanfanel, can you file this as a mutter bug?

https://gitlab.gnome.org/GNOME/mutter/-/issues

**Comment by vanfanel** [comment]
@flibitijibibo What should I do with regards to this? Any tests you want me to do?
(sorry if your previous comments contained that information somehow, my english is not perfect).

**Comment by sulix** [comment]
For what it's worth, I tried looking into whether we could use ``zwp_locked_pointer_v1_set_cursor_position_hint()`` to simulate mouse warping (I think this is roughly what Xwayland does, which seems to work), but it was very hacky, and didn't fix this issue. So I agree that scummvm will have not rely on SDL_WarpMouse() under wayland.

**Comment by flibitijibibo** [comment]
I've thrown together #4892 to where it _should_ at least be testable as an alternative to using WarpMouse, but probably still needs work. The Wayland side isn't done but should be MUCH easier to implement than X11. The PR is going to be free the whole weekend if anyone wants to take this down before 2.0.18 is tagged.

**Comment by flibitijibibo** [comment]
Bumping this to 2.0.20 since it's 50% WarpMouse which is invalid and 50% compositor which is `NOTOURBUG` - hopefully ConfineCursor will make this a non-issue for ScummVM when it's available, but we sort of have to ship it first...

**Comment by flibitijibibo** [comment]
The very latest SDL includes SDL_SetWindowMouseRect which is fully supported on Windows, macOS, X11, and Wayland. This may be the warpless solution the ScummVM devs are looking for, but it's worth pointing out that this new function uses the same mechanisms as SetWindowGrab internally and sure enough it's busted on GNOME in the exact same way, so I'm like 99.99% sure we're looking at two bugs:

- Bad clip rectangle? Blame the compositor.
- No clip rectangle? Blame dependency on WarpMouse.

Once ScummVM's fixed the latter we can focus on the former.

**Comment by ccawley2011** [comment]
I've opened https://github.com/scummvm/scummvm/pull/3546, which should fix the issue on ScummVM's side.

**Comment by flibitijibibo** [comment]
Checked this out with the latest ScummVM and SDL and can confirm the mouse rect confines correctly in Wayland now.

I've filed the Mutter issue here: https://gitlab.gnome.org/GNOME/mutter/-/issues/2110

**Comment by vanfanel** [comment]
@flibitijibibo I have tried Scummvm on Wayland+Weston, latest Scummvm GIT code, latest SDL2 stable (SDL2-2.24.0) and I still see the cursor stuck on the left and right sides of the screen when aspect ratio correction is activated.

I read the entire conversation several times, but I still don't get if it was supposed to be fixed at a compositor level: Scummvm must be using  SDL_SetWindowMouseRect() by now, so at the Scummvm level everything should be ok.

The same problem also happens on tinywl, the example compositor included with WLRoots sources. 

So, is it a Weston/WLRoots thing now?
This is very strange.
