### ISSUE TITLE
Better multi-monitor support on Xorg/Linux

### ISSUE THREAD

**Issue by YellowOnion** [libsdl-org/SDL#4827]
I'm not really sure this is the correct place to report/ask this, but since SDL2 is used by basically every game, maybe SDL2 can resolve this by providing some better heuristics to fix the abysmal multi monitor support and acting as a template for other game Engines to do it correctly in native Linux games (Wine ironically doesn't seem to have any of these issues)

I currently have two monitors,

My current problem is that most if not all my native Linux games are put on the secondary display because my secondary display is at 0,0 because of my desk placement and ergonomics I cannot put my secondary display to the right.

Dota 2: Launches on the secondary display: in Full-screen mode I can move it to the primary, and but if I minimize it moves back to the secondary. if borderless window the window is stuck on my secondary display gnome refuses to move to primary display, at 1080p on my 1200p monitor, the out of bounds data is rendered as junk. `-sdl_displayindex` doesn't work, and seems to be specific to the game engine, not "idiot dev" proof.

Factorio provides some useful information:
```
   0.084 Available displays: 2
   0.084  [0]: DELL P2314H 23" - {[1920,0], 1920x1080, SDL_PIXELFORMAT_RGB888, 60Hz}
   0.084  [1]: Philips 240B 24" - {[0,111], 1920x1200, SDL_PIXELFORMAT_RGB888, 60Hz}
```
It enumerates it correctly, and even has the monitor I want as primary in index 0, but it still detects my Philips incorrectly as my "primary".

With Unity games: If I move the window to the primary display the game has incorrect mouse clicks, the cursor position seems to have a y offset of 120px either related to the display layout, or the way in which renders to the 1200p monitor and doesn't fix/register the size change.

This also breaks: triple monitor setups where you would want the center monitor as the primary monitor. Setups with the secondary above the primary (i.e. a TV for watching videos)

![image](https://user-images.githubusercontent.com/364160/136873837-879eea1b-67bd-4aed-ab3f-1debd6469a5e.png)

```
xrandr --current                                                                                                                     ~
Screen 0: minimum 320 x 200, current 3840 x 1200, maximum 16384 x 16384
DisplayPort-0 connected primary 1920x1080+1920+120 (normal left inverted right x axis y axis) 509mm x 286mm
   1920x1080     60.00*+
   1680x1050     60.00  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1440x900      60.00  
   1280x800      60.00  
   1152x864      75.00  
   1280x720      60.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
   720x400       70.08  
DisplayPort-1 disconnected (normal left inverted right x axis y axis)
HDMI-A-0 disconnected (normal left inverted right x axis y axis)
HDMI-A-1 disconnected (normal left inverted right x axis y axis)
DVI-D-0 connected 1920x1200+0+0 (normal left inverted right x axis y axis) 519mm x 324mm
   1920x1200     59.95*+
   1920x1080     59.95  
   1600x1200     60.00  
   1680x1050     59.88  
   1280x1024     75.02  
   1440x900      74.98    59.90  
   1280x960      60.00  
   1280x800      59.95  
   1152x864      75.00  
   1280x720      60.00  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    72.81    66.67    59.94  
   720x400       70.08  
```

**Comment by icculus** [comment]
I assume the correct thing to do is fish this information out of Gnome's settings, if possible, and then figure out how to map that to an X11 (and separate from this specific issue, Wayland) display. It likely has no direct X11 mechanism we can query.

Pulling out the setting from Gnome is probably fairly trivial. Mapping to an X11 display may not be. I have to research it, and this is likely going to bump to 2.0.24 before we get it in revision control.

(Also: KDE may or may not have different settings for this.)

**Comment by icculus** [comment]
This isn't going to make 2.0.22.

**Comment by icculus** [comment]
Just looking at this quickly as I'm sifting through milestone bugs...so the X11 code already (in the XRandR codepath, at least) has code to determine the primary monitor, which _is_ apparently reported at the X11 level without us having to talk to Gnome, and it makes sure that that monitor is listed as display 0...Factorio's output seems to confirm this.

So it's _not_ that SDL is failing to find the primary monitor, it's that (for whatever reason) we're putting windows on the wrong one. This might be for several reasons, but it's extremely likely that most games are just going to call SDL_CreateWindow() with a position of CENTERED or UNDEFINED, which _should_ put it on the primary display by default...so the bug is likely elsewhere (in SDL's x11 code), but I don't have more information yet.

Perhaps our fullscreen code is assuming the primary monitor's origin is (0, 0)...?

**Comment by YellowOnion** [comment]
Is there anything I can do to help with this? I know a little C.

**Comment by slouken** [comment]
FYI, It looks like this is fixed in SDL3. At least on my system, if I run `test/testwm --info all`, I get:
```
INFO: Number of displays: 2
INFO: Display 1: ASUS PA329CV 32"
INFO: Bounds: 3840x2160 at 3840,329
INFO: Usable bounds: 3840x2133 at 3840,356
INFO: Display 2: ASUS PA329CV 32"
INFO: Bounds: 3840x2160 at 0,0
INFO: Usable bounds: 3840x1804 at 0,356
```
If I run `test/testwm --fullscreen-desktop --display 1`, it will go on my primary monitor, and if I run with `--display 2`, it will go on my left monitor.

**Comment by flying-sheep** [comment]
So SDL3 improved this in the sense that `SDL_DisplayID`s are at least stable for a single session. But they are still not stable across reboots, I assume.

What is is the adapter names:

```nushell
❯ ls /sys/class/drm | get name
╭───┬──────────────────────────────────╮
│ 0 │ /sys/class/drm/renderD128        │
│ 1 │ /sys/class/drm/card1             │
│ 2 │ /sys/class/drm/card1-HDMI-A-1    │
│ 3 │ /sys/class/drm/card1-DP-2        │
│ 4 │ /sys/class/drm/card1-Writeback-1 │
│ 5 │ /sys/class/drm/card1-DP-3        │
│ 6 │ /sys/class/drm/version           │
│ 7 │ /sys/class/drm/card1-DP-1        │
╰───┴──────────────────────────────────╯
```

in my case that’s `DP-1`, `DP-2`, `DP-3`, and `HDMI-A-1`.

SDL2 uses them in the display name, but for some reason adds the display size with no way to just get the adapter name. E.g. my main screen is `DP-1 34"`.

Does SDL3 have a way to get a display’s WM identifier without adding stuff?

**Comment by ssokolow** [comment]
> which is apparently reported at the X11 level without us having to talk to Gnome

Yeah. The simplest way to check that is probably to run `xrandr` and see which input has `primary` in its line of details. (`DP-3` in my case as seen below.)

```
ssokolow@monolith-tng ~ % xrandr
Screen 0: minimum 8 x 8, current 4480 x 1080, maximum 32767 x 32767
HDMI-0 connected 1280x1024+3200+0 (normal left inverted right x axis y axis) 376mm x 301mm
   1280x1024     60.02*+  75.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 connected 1280x1024+0+0 (normal left inverted right x axis y axis) 376mm x 301mm
   1280x1024     60.02*+  76.00    75.02    72.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32  
   640x480       75.00    72.81    59.94  
   640x350       70.07  
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 connected primary 1920x1080+1280+0 (normal left inverted right x axis y axis) 479mm x 269mm
   1920x1080     60.00*+
   1680x1050     59.95  
   1600x1200     60.00  
   1440x900      59.89  
   1280x1024     60.02  
   1280x960      60.00  
   1280x720      60.00  
   1024x768      60.00  
   800x600       60.32  
   640x480       59.94  
DP-4 disconnected (normal left inverted right x axis y axis)
DP-5 disconnected (normal left inverted right x axis y axis)
```

**Comment by Pshemas** [comment]
tried several options (both with `-O` and  display index, but on my end I can't make it work on Gnome 48, Wayland. Hope this is achievable somehow - it would definitely solve a major pita on my end.

Mind I'm super new to Gamescope and so far managed to only use Wayland backend. When I try 

```
gamescope -W 640 -H 480 --backend sdl -O HDMI-1 -- glxgears
```

I get:
```
gamescope: types/wlr_linux_dmabuf_v1.c:532: feedback_compile: Assertion `table_len > 0' failed.
```
