### ISSUE TITLE
[Bug][macOS] failed assertion `drawable must not be nil.'

### ISSUE THREAD

**Issue by andreiverdes** [libsdl-org/SDL#4863]
An Android screen mirroring tool called `scrcpy` using SDL, is crashing on macOS Big Sur and macOS Monterey.

```
INFO: scrcpy 1.19 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.19/share/scrcpy/scrcpy-serv...e pushed, 0 skipped. 15.6 MB/s (37330 bytes in 0.002s
INFO: Device: Google Pixel 3 (Android 12)
INFO: Renderer: metal
INFO: Initial texture: 1080x2160
[CAMetalLayer nextDrawable] returning nil due to 1 second timeout. Set allowsNextDrawableTimeout to keep retrying.
-[_MTLCommandBuffer presentDrawable:]:602: failed assertion `drawable must not be nil.'
zsh: abort      scrcpy
```
```
2021-10-22 13:26:51.874 scrcpy[44504:641745] INFO: scrcpy 1.19 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.19/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 77.3 MB/s (37330 bytes in 0.000s)
[server] INFO: Device: OnePlus LE2123 (Android 11)
2021-10-22 13:26:52.343 scrcpy[44504:641745] INFO: Renderer: metal
2021-10-22 13:26:52.346 scrcpy[44504:641745] INFO: Initial texture: 1440x3216
2021-10-22 13:33:21.959 scrcpy[44504:641745] [CAMetalLayer nextDrawable] returning nil due to 1 second timeout. Set allowsNextDrawableTimeout to keep retrying.
-[_MTLCommandBuffer presentDrawable:]:660: failed assertion `drawable must not be nil.'
[1]    44504 abort      scrcpy
```

More details : 
https://github.com/Genymobile/scrcpy/issues/2698

Please let me know if I can provide any more info or assist in debugging this!

**Comment by icculus** [comment]
I've only tried on a Mojave install, but testsprite2, when minimized, just gets an extremely fast framerate (Metal just throws away the rendering work when minimized, I think), so it's not minimization but itself causing it.

I'll have to try this on the Big Sur box with an actual copy of the software in question to see if it reproduces.

**Comment by andreiverdes** [comment]
I used it very frequently in Mojave and had no issues. I thing the problem is with Big Sur onwards. I have Monterey. If is there anything I could do to help, please let me know. I appreciate your time looking into this and the updates!

**Comment by icculus** [comment]
Waiting on https://github.com/icculus/SDL/commit/aa93cc13637ad2c8177864bd9bf36abb754f001d to pass build checks, then it would be useful if someone could try it and see if it fixes this issue.

**Comment by icculus** [comment]
Actually, to make it easier, I merged it now that the CI passed. Please try the latest SDL and see if the problem goes away! And if not, we'll reopen this bug, but it shouldn't try to present a nil drawable any more in any case.

**Comment by andreiverdes** [comment]
Will give it a try, thank you!

**Comment by andreiverdes** [comment]
Tested this on Monterey. Everything looks fine now, I'm still getting the Metal warning but it's not crashing anymore. Thanks @icculus for your time into fixing this!
