### ISSUE TITLE
Win10: SDL_JoystickIsHaptic always returns false. Joysticks listed in SDL_NumHaptics instead

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#4911]
I'm not sure when this started happening, but I'm using the latest source, built with VS2019. Many other strange things are going on, I'll try to explain:

Testing various controllers, none of them are SDL_JoystickIsHaptic, but they all have rumble. They are listed under separately under SDL_NumHaptics as "XInput Controller". This doesn't seem to happen on Android, so I guess it's a Windows thing.

Other problems that might be related to this:

Rumble does nothing until an axis is moved or button is pressed.

My Xbox One controller is now being listed as two controllers: "Controller (Xbox One For Windows)" and the usual "Xbox One Game Controller". <-- this might have happened as a result of a Windows 10 update recently.

I've been wrestling with this for days and can't seem to influence it with hints. Nobody replies on the SDL forums about joysticks.

**Comment by slouken** [comment]
@AntTheAlchemist I think it makes sense to set up a call and go over the controller issues you're seeing. Can you send me a meeting invite at slouken@libsdl.org?

**Comment by cgutman** [comment]
There's a good chance that this is a duplicate of #4914. It sounds like WGI is reliably winning the race against RawInput on your system, which leads to the duplicated device.

"Controller (Xbox One For Windows)" is the name that the RawInput backend uses for an Xbox One controller and "Xbox One Game Controller" is what the WGI backend calls the same device.

@AntTheAlchemist can you still reproduce this with the latest source?

**Comment by AntTheAlchemist** [comment]
> @AntTheAlchemist can you still reproduce this with the latest source?

I'm happy to report the duplicate controllers are fixed now - this must have been caused by the race issue. The other issues I listed still persist though.

>  I think it makes sense to set up a call and go over the controller issues you're seeing. 

Sam, I'm happy to help, but nervous about setting up a meeting? I've never done any kind of conferencing before. It's gone 2am in England and I need sleep now. I think it should be really easy to reproduce. I played around more and this is what's happening:

No controllers have haptic any more. I remember they used to, and I could open them with SDL_HapticOpenFromJoystick().

If controllers are already plugged in when you run an app, they are listed under SDL_NumHaptics(), even though they're not showing as SDL_JoystickIsHaptic(). When you unplug them, the haptic devices persist. It's as off haptics are not hot-pluggable.

**Comment by slouken** [comment]
Gamepads as haptic devices has been broken for a while now. The way controllers are accessed has fundamentally changed since when this API was born, and DirectInput is no longer supported and actively discouraged by Microsoft:
https://docs.microsoft.com/en-us/windows/win32/xinput/xinput-and-directinput

The plan for 2.0.20 is to remove support for them entirely from the haptic API and suggest developers use the rumble API instead, since that more closely matches how most of them work. We will put some thought into that, since WGI is the recommended path forward for wheels and other controllers on Windows. We may simply rewrite the haptic system to use that as the back end going forward.

**Comment by cgutman** [comment]
> Testing various controllers, none of them are SDL_JoystickIsHaptic, but they all have rumble. They are listed under separately under SDL_NumHaptics as "XInput Controller". This doesn't seem to happen on Android, so I guess it's a Windows thing.

> If controllers are already plugged in when you run an app, they are listed under SDL_NumHaptics(), even though they're not showing as SDL_JoystickIsHaptic(). When you unplug them, the haptic devices persist. It's as off haptics are not hot-pluggable.

I tracked this down to the startup haptic enumeration logic that was decoupled from the joystick enumeration logic and fixed it in 715e7bda225226847565ae47a34e9144b8b2d76b. Now you should get no joystick haptic devices if you are using the (default) RawInput joystick backend rather than those orphaned haptic devices. If you disable `SDL_JOYSTICK_RAWINPUT`, then the XInput backend will pick up the joysticks and you'll get haptic devices again.

> The plan for 2.0.20 is to remove support for them entirely from the haptic API and suggest developers use the rumble API instead, since that more closely matches how most of them work. We will put some thought into that, since WGI is the recommended path forward for wheels and other controllers on Windows. We may simply rewrite the haptic system to use that as the back end going forward.

What are your thoughts on providing a compatibility with legacy code that uses `SDL_HapticOpenFromJoystick()` by creating virtual haptic devices that just pass through to the `JoystickRumble()` implementation? Poking around at that has been on my to-do list for a little while now.

**Comment by slouken** [comment]
> I tracked this down to the startup haptic enumeration logic that was decoupled from the joystick enumeration logic and fixed it in [715e7bd](https://github.com/libsdl-org/SDL/commit/715e7bda225226847565ae47a34e9144b8b2d76b). Now you should get no joystick haptic devices if you are using the (default) RawInput joystick backend rather than those orphaned haptic devices. If you disable `SDL_JOYSTICK_RAWINPUT`, then the XInput backend will pick up the joysticks and you'll get haptic devices again.

Great, thanks!

> What are your thoughts on providing compatibility with legacy code that uses `SDL_HapticOpenFromJoystick()` by creating virtual haptic devices that just pass through to the `JoystickRumble()` implementation? Poking around at that has been on my to-do list for a little while now.

I'm not opposed to that. I was mulling that over even as I was writing the above, and it's probably the right thing to do for legacy applications.

**Comment by slouken** [comment]
It looks like with @cgutman's fix, this issue is resolved for 2.0.18.

Thanks!

**Comment by AntTheAlchemist** [comment]
Much better, but still not 100%. `SDL_HapticOpenFromJoystick()` still doesn't work even with `SDL_HINT_JOYSTICK_RAWINPUT, "0"`. No problem though.

Does this mean `SDL_JoystickIsHaptic()` will be redundant? Can we have a `SDL_JoystickHasRumble()`?

**Comment by cgutman** [comment]
> Much better, but still not 100%. `SDL_HapticOpenFromJoystick()` still doesn't work even with `SDL_HINT_JOYSTICK_RAWINPUT, "0"`. No problem though.

Yep, we weren't creating haptic devices for joysticks present prior to initialization of the haptic subsystem (basically any joystick already plugged in). Fixed that in 6b64c47b69f2cb609668b919812c2ce3baf921be

> Does this mean `SDL_JoystickIsHaptic()` will be redundant? Can we have a `SDL_JoystickHasRumble()`?

@slouken what do you think about `SDL_JoystickHasRumble()`?

I've certainly had a need for that in the past when trying to determine if `SDL_JoystickRumble()` was supported on a particular device. As a workaround, I've had to resort to using a very low intensity rumble `SDL_JoystickRumble(joystick, 1, 1, 1)` to see if rumble is supported.

For the haptic emulation via joystick rumble, we'll definitely need a function like that to determine which joysticks should get a associated haptic device.

**Comment by slouken** [comment]
> > Does this mean `SDL_JoystickIsHaptic()` will be redundant? Can we have a `SDL_JoystickHasRumble()`?
> 
> @slouken what do you think about `SDL_JoystickHasRumble()`?

Sure, sounds good.
