### ISSUE TITLE
SDL_GetDisplayName does not return real monitor name (Windows)

### ISSUE THREAD

**Issue by thrust26** [libsdl-org/SDL#5321]
When testing with Windows 10, `SDL_GetDisplayName` always returns "Generic Pnp Monitor". This is the name which is displayed in the Device Manager too. But Windows also knows the real names of its monitors (e.g. "Samsung bla 123"), which can be seen e.g. in Printers and Devices.

It would be nice if `SDL_GetDisplayName` would return these names. This would be be helpful e.g. when you are using multiple, different monitors.

**Comment by icculus** [comment]
I'm going to put this in 2.0.22, under the assumption there's a win32 API that provides this information.

If this is going to take herculean efforts to pull the info out of an undocumented Registry key, let's bump this back out of the milestone, though.

**Comment by thrust26** [comment]
Here is some info:
https://stackoverflow.com/questions/4958683/how-do-i-get-the-actual-monitor-name-as-seen-in-the-resolution-dialog

**Comment by icculus** [comment]
Fixed this up to build on older SDKs and presumably keep running on WinXP. Done!

**Comment by thrust26** [comment]
Has this been added to the 2.24 release? I am still getting "Generic Pnp Monitor".
