### ISSUE TITLE
In 2.0.20, SDL_PollEvent(NULL) does not return 1 when events are pending

### ISSUE THREAD

**Issue by blast007** [libsdl-org/SDL#5350]
In BZFlag, we noticed that our game was ignoring input and showing an unresponsive application message on Linux distributions that had updated to SDL 2.0.20.  We also confirmed the same issue on macOS and and a user confirmed it on FreeBSD.  We have been using SDL_PollEvent(NULL) to check if there are any pending events before we enter our event handling code.  This worked up until SDL 2.0.20, where the function stopped returning 1 if there were pending events.

I used the Debian's code search to find other games/software that used SDL_PollEvent(NULL) and most of them seem to manually call SDL_PumpEvents() on a regular basis, which seems to work around the problem.  Of the software I found, I only saw the same problem in mirrormagic, which did not call SDL_PumpEvents() regularly.

I modified testmouse.c from the SDL source to wrap the event handling loop in ```if (SDL_PollEvent(NULL) == 1) {``` and it then also fails under SDL 2.0.20.
https://gist.github.com/blast007/477d1d07f6dc470990217dec30d8e037

I had run a git bisect between SDL 2.0.18 and SDL 2.0.20, and that showed that the issue for us began starting with [Move special sentinel handling inside SDL_PeepEvents()](https://github.com/libsdl-org/SDL/commit/954858846d2883864b4e5fef55f31bb92f1514cc)

Other links:
[Our issue tracking the problem](https://github.com/BZFlag-Dev/bzflag/issues/301)
[Our workaround](https://github.com/BZFlag-Dev/bzflag/commit/d7005c4777945bded0e386750ac45d4ee166f33f)

**Comment by slouken** [comment]
This should be fixed in the current code in git. Can you confirm?

**Comment by blast007** [comment]
No, I tried BZFlag 2.4.22 with SDL2 git main branch revision 18032979d892639ad4e03584a40a4d205cd2f5fd and the issue persists.  The modification I made to testmouse.c also continues to have the issue with that SDL revision.

**Comment by cosmicchipsocket** [comment]
+1. I'm also having this issue on Windows. Versions 2.0.14 and 2.0.16 seem to be working fine. Versions 2.0.18 and 2.0.20 have the bug.

I'm using the Rust bindings, which panic if SDL_PollEvent(NULL) does not return 1. When this happens, the SDL error is blank.

**Comment by slouken** [comment]
Thanks for the good test case. I think this is fixed, can you confirm?

**Comment by blast007** [comment]
We confirmed it's now working on both Linux and macOS, so I imagine we're good on other platforms too.

**Comment by slouken** [comment]
Thanks!
