### ISSUE TITLE
Android compilation failed

### ISSUE THREAD

**Issue by mingmoe** [libsdl-org/SDL#5950]
I'm using android ndk `r25` to compile SDL `v2.0.22` in Windows11. 

I use `Android (8490178, based on r450784d) clang version 14.0.6` and CMake `v3.23.1` to build. But got some warnings.

Because `-Werror`, the warnings change into errors.

likes:
```
FAILED: CMakeFiles/SDL2.dir/src/core/android/SDL_android.c.o 
C:/path/to/SDL/src/core/android/SDL_android.c:515:13: error: mixing declarations and code is incompatible with standards before C99 [-Werror,-Wdeclaration-after-statement]
    JNIEnv *env = NULL;
            ^

C:/path/to/SDL/src/core/android/SDL_android.c:2564:13: error: mixing declarations and code is incompatible with standards before C99 [-Werror,-Wdeclaration-after-statement]

    jstring jpermission = (*env)->NewStringUTF(env, permission);

            ^

2 errors generated.

```

The `-Wdeclaration-after-statement` option is added by `CMakeLists.txt`. Not from system.

When I hack it and delete it.The building will be successful.

Any idea for build system or compiler? (BTW,I build SDL for Windows successfully.)

**Comment by sezero** [comment]
Already fixed in git. E.g.:
https://github.com/libsdl-org/SDL/commit/fd2a2eea108347237af35a3bc39f076d2c129417

**Comment by mingmoe** [comment]
Still exists. Note:I'm using main branch now.
Full Log:https://paste.ubuntu.com/p/q3ySSYG4VJ/
@sezero

**Comment by sezero** [comment]
Does the following patch fix it?
```diff
diff --git a/src/audio/aaudio/SDL_aaudio.c b/src/audio/aaudio/SDL_aaudio.c
index 1d1553b..4f7371d 100644
--- a/src/audio/aaudio/SDL_aaudio.c
+++ b/src/audio/aaudio/SDL_aaudio.c
@@ -437,11 +437,13 @@ void aaudio_ResumeDevices(void)
 */
 SDL_bool aaudio_DetectBrokenPlayState( void )
 {
+    struct SDL_PrivateAudioData *private;
+
     if ( !audioDevice || !audioDevice->hidden ) {
         return SDL_FALSE;
     }
 
-    struct SDL_PrivateAudioData *private = audioDevice->hidden;
+    private = audioDevice->hidden;
 
     int64_t framePosition, timeNanoseconds;
     aaudio_result_t res = ctx.AAudioStream_getTimestamp( private->stream, CLOCK_MONOTONIC, &framePosition, &timeNanoseconds );
diff --git a/src/audio/openslES/SDL_openslES.c b/src/audio/openslES/SDL_openslES.c
index 39d64b2..c3b3e97 100644
--- a/src/audio/openslES/SDL_openslES.c
+++ b/src/audio/openslES/SDL_openslES.c
@@ -131,6 +131,8 @@ static void openslES_DestroyEngine(void)
 static int
 openslES_CreateEngine(void)
 {
+    const SLInterfaceID ids[1] = { SL_IID_VOLUME };
+    const SLboolean req[1] = { SL_BOOLEAN_FALSE };
     SLresult result;
 
     LOGI("openSLES_CreateEngine()");
@@ -160,8 +162,6 @@ openslES_CreateEngine(void)
     LOGI("EngineGetInterface OK");
 
     /* create output mix */
-    const SLInterfaceID ids[1] = { SL_IID_VOLUME };
-    const SLboolean req[1] = { SL_BOOLEAN_FALSE };
     result = (*engineEngine)->CreateOutputMix(engineEngine, &outputMixObject, 1, ids, req);
     if (SL_RESULT_SUCCESS != result) {
         LOGE("CreateOutputMix failed: %d", result);
@@ -229,6 +229,8 @@ openslES_CreatePCMRecorder(_THIS)
 {
     struct SDL_PrivateAudioData *audiodata = this->hidden;
     SLDataFormat_PCM format_pcm;
+    SLDataLocator_AndroidSimpleBufferQueue loc_bufq;
+    SLDataSink audioSnk;
     SLresult result;
     int i;
 
@@ -254,7 +256,8 @@ openslES_CreatePCMRecorder(_THIS)
     SLDataSource audioSrc = {&loc_dev, NULL};
 
     /* configure audio sink */
-    SLDataLocator_AndroidSimpleBufferQueue loc_bufq = { SL_DATALOCATOR_ANDROIDSIMPLEBUFFERQUEUE, NUM_BUFFERS };
+    loc_bufq.locatorType = SL_DATALOCATOR_ANDROIDSIMPLEBUFFERQUEUE;
+    loc_bufq.numBuffers = NUM_BUFFERS;
 
     format_pcm.formatType    = SL_DATAFORMAT_PCM;
     format_pcm.numChannels   = this->spec.channels;
@@ -264,7 +267,8 @@ openslES_CreatePCMRecorder(_THIS)
     format_pcm.endianness    = SL_BYTEORDER_LITTLEENDIAN;
     format_pcm.channelMask   = SL_SPEAKER_FRONT_CENTER;
 
-    SLDataSink audioSnk = { &loc_bufq, &format_pcm };
+    audioSnk.pLocator = &loc_bufq;
+    audioSnk.pFormat = &format_pcm;
 
     /* create audio recorder */
     /* (requires the RECORD_AUDIO permission) */
@@ -406,6 +410,7 @@ static int
 openslES_CreatePCMPlayer(_THIS)
 {
     struct SDL_PrivateAudioData *audiodata = this->hidden;
+    SLDataLocator_AndroidSimpleBufferQueue loc_bufq;
     SLDataFormat_PCM format_pcm;
     SLAndroidDataFormat_PCM_EX format_pcm_ex;
     SLresult result;
@@ -442,7 +447,8 @@ openslES_CreatePCMPlayer(_THIS)
           this->spec.channels, (this->spec.format & 0x1000) ? "BE" : "LE", this->spec.samples);
 
     /* configure audio source */
-    SLDataLocator_AndroidSimpleBufferQueue loc_bufq = { SL_DATALOCATOR_ANDROIDSIMPLEBUFFERQUEUE, NUM_BUFFERS };
+    loc_bufq.locatorType = SL_DATALOCATOR_ANDROIDSIMPLEBUFFERQUEUE;
+    loc_bufq.numBuffers = NUM_BUFFERS;
 
     format_pcm.formatType    = SL_DATAFORMAT_PCM;
     format_pcm.numChannels   = this->spec.channels;
```

**Comment by mingmoe** [comment]
Fix.....but...still exists somewhere.
https://paste.ubuntu.com/p/CWBsBgn3D7/

**Comment by mingmoe** [comment]
BTW, SDL use `ndk-r21e` in github action, update maybe a good idea.

latest version is `r25`. It's also a **LTS** version.

**Comment by sezero** [comment]
OK, updated patch below, hopefully complete this time.

```diff
diff --git a/src/audio/aaudio/SDL_aaudio.c b/src/audio/aaudio/SDL_aaudio.c
index 1d1553b..5f31866 100644
--- a/src/audio/aaudio/SDL_aaudio.c
+++ b/src/audio/aaudio/SDL_aaudio.c
@@ -437,14 +437,17 @@ void aaudio_ResumeDevices(void)
 */
 SDL_bool aaudio_DetectBrokenPlayState( void )
 {
+    struct SDL_PrivateAudioData *private;
+    int64_t framePosition, timeNanoseconds;
+    aaudio_result_t res;
+
     if ( !audioDevice || !audioDevice->hidden ) {
         return SDL_FALSE;
     }
 
-    struct SDL_PrivateAudioData *private = audioDevice->hidden;
+    private = audioDevice->hidden;
 
-    int64_t framePosition, timeNanoseconds;
-    aaudio_result_t res = ctx.AAudioStream_getTimestamp( private->stream, CLOCK_MONOTONIC, &framePosition, &timeNanoseconds );
+    res = ctx.AAudioStream_getTimestamp( private->stream, CLOCK_MONOTONIC, &framePosition, &timeNanoseconds );
     if ( res == AAUDIO_ERROR_INVALID_STATE ) {
         aaudio_stream_state_t currentState = ctx.AAudioStream_getState( private->stream );
         /* AAudioStream_getTimestamp() will also return AAUDIO_ERROR_INVALID_STATE while the stream is still initially starting. But we only care if it silently went invalid while playing. */
diff --git a/src/audio/openslES/SDL_openslES.c b/src/audio/openslES/SDL_openslES.c
index 39d64b2..517aeef 100644
--- a/src/audio/openslES/SDL_openslES.c
+++ b/src/audio/openslES/SDL_openslES.c
@@ -131,6 +131,8 @@ static void openslES_DestroyEngine(void)
 static int
 openslES_CreateEngine(void)
 {
+    const SLInterfaceID ids[1] = { SL_IID_VOLUME };
+    const SLboolean req[1] = { SL_BOOLEAN_FALSE };
     SLresult result;
 
     LOGI("openSLES_CreateEngine()");
@@ -160,8 +162,6 @@ openslES_CreateEngine(void)
     LOGI("EngineGetInterface OK");
 
     /* create output mix */
-    const SLInterfaceID ids[1] = { SL_IID_VOLUME };
-    const SLboolean req[1] = { SL_BOOLEAN_FALSE };
     result = (*engineEngine)->CreateOutputMix(engineEngine, &outputMixObject, 1, ids, req);
     if (SL_RESULT_SUCCESS != result) {
         LOGE("CreateOutputMix failed: %d", result);
@@ -229,6 +229,10 @@ openslES_CreatePCMRecorder(_THIS)
 {
     struct SDL_PrivateAudioData *audiodata = this->hidden;
     SLDataFormat_PCM format_pcm;
+    SLDataLocator_AndroidSimpleBufferQueue loc_bufq;
+    SLDataSink audioSnk;
+    const SLInterfaceID ids[1] = { SL_IID_ANDROIDSIMPLEBUFFERQUEUE };
+    const SLboolean req[1] = { SL_BOOLEAN_TRUE };
     SLresult result;
     int i;
 
@@ -254,7 +258,8 @@ openslES_CreatePCMRecorder(_THIS)
     SLDataSource audioSrc = {&loc_dev, NULL};
 
     /* configure audio sink */
-    SLDataLocator_AndroidSimpleBufferQueue loc_bufq = { SL_DATALOCATOR_ANDROIDSIMPLEBUFFERQUEUE, NUM_BUFFERS };
+    loc_bufq.locatorType = SL_DATALOCATOR_ANDROIDSIMPLEBUFFERQUEUE;
+    loc_bufq.numBuffers = NUM_BUFFERS;
 
     format_pcm.formatType    = SL_DATAFORMAT_PCM;
     format_pcm.numChannels   = this->spec.channels;
@@ -264,17 +269,11 @@ openslES_CreatePCMRecorder(_THIS)
     format_pcm.endianness    = SL_BYTEORDER_LITTLEENDIAN;
     format_pcm.channelMask   = SL_SPEAKER_FRONT_CENTER;
 
-    SLDataSink audioSnk = { &loc_bufq, &format_pcm };
+    audioSnk.pLocator = &loc_bufq;
+    audioSnk.pFormat = &format_pcm;
 
     /* create audio recorder */
     /* (requires the RECORD_AUDIO permission) */
-    const SLInterfaceID ids[1] = {
-        SL_IID_ANDROIDSIMPLEBUFFERQUEUE,
-    };
-    const SLboolean req[1] = {
-        SL_BOOLEAN_TRUE,
-    };
-
     result = (*engineEngine)->CreateAudioRecorder(engineEngine, &recorderObject, &audioSrc, &audioSnk, 1, ids, req);
     if (SL_RESULT_SUCCESS != result) {
         LOGE("CreateAudioRecorder failed: %d", result);
@@ -354,7 +353,6 @@ openslES_CreatePCMRecorder(_THIS)
     return 0;
 
 failed:
-
     return SDL_SetError("Open device failed!");
 }
 
@@ -384,7 +382,6 @@ openslES_DestroyPCMPlayer(_THIS)
 
     /* destroy buffer queue audio player object, and invalidate all associated interfaces */
     if (bqPlayerObject != NULL) {
-
         (*bqPlayerObject)->Destroy(bqPlayerObject);
 
         bqPlayerObject = NULL;
@@ -406,8 +403,14 @@ static int
 openslES_CreatePCMPlayer(_THIS)
 {
     struct SDL_PrivateAudioData *audiodata = this->hidden;
+    SLDataLocator_AndroidSimpleBufferQueue loc_bufq;
     SLDataFormat_PCM format_pcm;
     SLAndroidDataFormat_PCM_EX format_pcm_ex;
+    SLDataSource audioSrc;
+    SLDataSink audioSnk;
+    SLDataLocator_OutputMix loc_outmix;
+    const SLInterfaceID ids[2] = { SL_IID_ANDROIDSIMPLEBUFFERQUEUE, SL_IID_VOLUME };
+    const SLboolean req[2] = { SL_BOOLEAN_TRUE, SL_BOOLEAN_FALSE };
     SLresult result;
     int i;
 
@@ -442,7 +445,8 @@ openslES_CreatePCMPlayer(_THIS)
           this->spec.channels, (this->spec.format & 0x1000) ? "BE" : "LE", this->spec.samples);
 
     /* configure audio source */
-    SLDataLocator_AndroidSimpleBufferQueue loc_bufq = { SL_DATALOCATOR_ANDROIDSIMPLEBUFFERQUEUE, NUM_BUFFERS };
+    loc_bufq.locatorType = SL_DATALOCATOR_ANDROIDSIMPLEBUFFERQUEUE;
+    loc_bufq.numBuffers = NUM_BUFFERS;
 
     format_pcm.formatType    = SL_DATAFORMAT_PCM;
     format_pcm.numChannels   = this->spec.channels;
@@ -501,23 +505,16 @@ openslES_CreatePCMPlayer(_THIS)
         format_pcm_ex.representation = SL_ANDROID_PCM_REPRESENTATION_FLOAT;
     }
 
-    SLDataSource audioSrc = { &loc_bufq, SDL_AUDIO_ISFLOAT(this->spec.format) ? (void*)&format_pcm_ex : (void*)&format_pcm };
+    audioSrc.pLocator = &loc_bufq;
+    audioSrc.pFormat = SDL_AUDIO_ISFLOAT(this->spec.format) ? (void*)&format_pcm_ex : (void*)&format_pcm;
 
     /* configure audio sink */
-    SLDataLocator_OutputMix loc_outmix = { SL_DATALOCATOR_OUTPUTMIX, outputMixObject };
-    SLDataSink audioSnk = { &loc_outmix, NULL };
+    loc_outmix.locatorType = SL_DATALOCATOR_OUTPUTMIX;
+    loc_outmix.outputMix = outputMixObject;
+    audioSnk.pLocator = &loc_outmix;
+    audioSnk.pFormat = NULL;
 
     /* create audio player */
-    const SLInterfaceID ids[2] = {
-        SL_IID_ANDROIDSIMPLEBUFFERQUEUE,
-        SL_IID_VOLUME
-    };
-
-    const SLboolean req[2] = {
-        SL_BOOLEAN_TRUE,
-        SL_BOOLEAN_FALSE,
-    };
-
     result = (*engineEngine)->CreateAudioPlayer(engineEngine, &bqPlayerObject, &audioSrc, &audioSnk, 2, ids, req);
     if (SL_RESULT_SUCCESS != result) {
         LOGE("CreateAudioPlayer failed: %d", result);
@@ -590,7 +587,6 @@ openslES_CreatePCMPlayer(_THIS)
     return 0;
 
 failed:
-
     return -1;
 }
 
```

**Comment by mingmoe** [comment]
hope this is the last error. *:-)*
```
FAILED: CMakeFiles/SDL2.dir/src/audio/openslES/SDL_openslES.c.o 
C:\DirectProgram\Tools\android-ndk-r25\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe --target=aarch64-none-linux-android28 --sysroot=C:/DirectProgram/Tools/android-ndk-r25/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DGL_GLEXT_PROTOTYPES -DSDL2_EXPORTS -DUSING_GENERATED_CONFIG_H -IC:/Users/mingm/Projects/utopia-cpp/utopia/library/build/android-arm64-Debug/SDL/include -IC:/Users/mingm/Projects/utopia-cpp/utopia/library/build/android-arm64-Debug/SDL/include-config-debug -IC:/DirectProgram/Tools/android-ndk-r25/sources/android/cpufeatures -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -idirafter "C:/Users/mingm/Projects/utopia-cpp/utopia/library/SDL/src/video/khronos"  -Wall -fno-strict-aliasing -Werror=declaration-after-statement -Wdeclaration-after-statement -fvisibility=hidden -Wshadow -fcolor-diagnostics  -DSDL_BUILD_MAJOR_VERSION=2 -DSDL_BUILD_MINOR_VERSION=23 -DSDL_BUILD_MICRO_VERSION=1 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/SDL2.dir/src/audio/openslES/SDL_openslES.c.o -MF CMakeFiles\SDL2.dir\src\audio\openslES\SDL_openslES.c.o.d -o CMakeFiles/SDL2.dir/src/audio/openslES/SDL_openslES.c.o -c C:/Users/mingm/Projects/utopia-cpp/utopia/library/SDL/src/audio/openslES/SDL_openslES.c
C:/Users/mingm/Projects/utopia-cpp/utopia/library/SDL/src/audio/openslES/SDL_openslES.c:257:28: error: mixing declarations and code is incompatible with standards before C99 [-Werror,-Wdeclaration-after-statement]

    SLDataLocator_IODevice loc_dev = {SL_DATALOCATOR_IODEVICE, SL_IODEVICE_AUDIOINPUT, SL_DEFAULTDEVICEID_AUDIOINPUT, NULL};

                           ^

1 error generated.
```

**Comment by sezero** [comment]
> hope this is the last error. _:-)_

Can't you do a `make -k` or some equivalent of it so that we can see all errors?
As you might have guessed, I'm doing this blindly for now i.e. no testing at all..

Anyways, updated patch below.

```diff
diff --git a/src/audio/aaudio/SDL_aaudio.c b/src/audio/aaudio/SDL_aaudio.c
index 1d1553b..5f31866 100644
--- a/src/audio/aaudio/SDL_aaudio.c
+++ b/src/audio/aaudio/SDL_aaudio.c
@@ -437,14 +437,17 @@ void aaudio_ResumeDevices(void)
 */
 SDL_bool aaudio_DetectBrokenPlayState( void )
 {
+    struct SDL_PrivateAudioData *private;
+    int64_t framePosition, timeNanoseconds;
+    aaudio_result_t res;
+
     if ( !audioDevice || !audioDevice->hidden ) {
         return SDL_FALSE;
     }
 
-    struct SDL_PrivateAudioData *private = audioDevice->hidden;
+    private = audioDevice->hidden;
 
-    int64_t framePosition, timeNanoseconds;
-    aaudio_result_t res = ctx.AAudioStream_getTimestamp( private->stream, CLOCK_MONOTONIC, &framePosition, &timeNanoseconds );
+    res = ctx.AAudioStream_getTimestamp( private->stream, CLOCK_MONOTONIC, &framePosition, &timeNanoseconds );
     if ( res == AAUDIO_ERROR_INVALID_STATE ) {
         aaudio_stream_state_t currentState = ctx.AAudioStream_getState( private->stream );
         /* AAudioStream_getTimestamp() will also return AAUDIO_ERROR_INVALID_STATE while the stream is still initially starting. But we only care if it silently went invalid while playing. */
diff --git a/src/audio/openslES/SDL_openslES.c b/src/audio/openslES/SDL_openslES.c
index 39d64b2..474de3b 100644
--- a/src/audio/openslES/SDL_openslES.c
+++ b/src/audio/openslES/SDL_openslES.c
@@ -131,6 +131,8 @@ static void openslES_DestroyEngine(void)
 static int
 openslES_CreateEngine(void)
 {
+    const SLInterfaceID ids[1] = { SL_IID_VOLUME };
+    const SLboolean req[1] = { SL_BOOLEAN_FALSE };
     SLresult result;
 
     LOGI("openSLES_CreateEngine()");
@@ -160,8 +162,6 @@ openslES_CreateEngine(void)
     LOGI("EngineGetInterface OK");
 
     /* create output mix */
-    const SLInterfaceID ids[1] = { SL_IID_VOLUME };
-    const SLboolean req[1] = { SL_BOOLEAN_FALSE };
     result = (*engineEngine)->CreateOutputMix(engineEngine, &outputMixObject, 1, ids, req);
     if (SL_RESULT_SUCCESS != result) {
         LOGE("CreateOutputMix failed: %d", result);
@@ -229,6 +229,12 @@ openslES_CreatePCMRecorder(_THIS)
 {
     struct SDL_PrivateAudioData *audiodata = this->hidden;
     SLDataFormat_PCM format_pcm;
+    SLDataLocator_AndroidSimpleBufferQueue loc_bufq;
+    SLDataSink audioSnk;
+    SLDataLocator_IODevice loc_dev;
+    SLDataSource audioSrc;
+    const SLInterfaceID ids[1] = { SL_IID_ANDROIDSIMPLEBUFFERQUEUE };
+    const SLboolean req[1] = { SL_BOOLEAN_TRUE };
     SLresult result;
     int i;
 
@@ -250,11 +256,16 @@ openslES_CreatePCMRecorder(_THIS)
           this->spec.channels, (this->spec.format & 0x1000) ? "BE" : "LE", this->spec.samples);
 
     /* configure audio source */
-    SLDataLocator_IODevice loc_dev = {SL_DATALOCATOR_IODEVICE, SL_IODEVICE_AUDIOINPUT, SL_DEFAULTDEVICEID_AUDIOINPUT, NULL};
-    SLDataSource audioSrc = {&loc_dev, NULL};
+    loc_dev.locatorType = SL_DATALOCATOR_IODEVICE;
+    loc_dev.deviceType = SL_IODEVICE_AUDIOINPUT;
+    loc_dev.deviceID = SL_DEFAULTDEVICEID_AUDIOINPUT;
+    loc_dev.device = NULL;
+    audioSrc.pLocator = &loc_dev;
+    audioSrc.pFormat = NULL;
 
     /* configure audio sink */
-    SLDataLocator_AndroidSimpleBufferQueue loc_bufq = { SL_DATALOCATOR_ANDROIDSIMPLEBUFFERQUEUE, NUM_BUFFERS };
+    loc_bufq.locatorType = SL_DATALOCATOR_ANDROIDSIMPLEBUFFERQUEUE;
+    loc_bufq.numBuffers = NUM_BUFFERS;
 
     format_pcm.formatType    = SL_DATAFORMAT_PCM;
     format_pcm.numChannels   = this->spec.channels;
@@ -264,17 +275,11 @@ openslES_CreatePCMRecorder(_THIS)
     format_pcm.endianness    = SL_BYTEORDER_LITTLEENDIAN;
     format_pcm.channelMask   = SL_SPEAKER_FRONT_CENTER;
 
-    SLDataSink audioSnk = { &loc_bufq, &format_pcm };
+    audioSnk.pLocator = &loc_bufq;
+    audioSnk.pFormat = &format_pcm;
 
     /* create audio recorder */
     /* (requires the RECORD_AUDIO permission) */
-    const SLInterfaceID ids[1] = {
-        SL_IID_ANDROIDSIMPLEBUFFERQUEUE,
-    };
-    const SLboolean req[1] = {
-        SL_BOOLEAN_TRUE,
-    };
-
     result = (*engineEngine)->CreateAudioRecorder(engineEngine, &recorderObject, &audioSrc, &audioSnk, 1, ids, req);
     if (SL_RESULT_SUCCESS != result) {
         LOGE("CreateAudioRecorder failed: %d", result);
@@ -354,7 +359,6 @@ openslES_CreatePCMRecorder(_THIS)
     return 0;
 
 failed:
-
     return SDL_SetError("Open device failed!");
 }
 
@@ -384,7 +388,6 @@ openslES_DestroyPCMPlayer(_THIS)
 
     /* destroy buffer queue audio player object, and invalidate all associated interfaces */
     if (bqPlayerObject != NULL) {
-
         (*bqPlayerObject)->Destroy(bqPlayerObject);
 
         bqPlayerObject = NULL;
@@ -406,8 +409,14 @@ static int
 openslES_CreatePCMPlayer(_THIS)
 {
     struct SDL_PrivateAudioData *audiodata = this->hidden;
+    SLDataLocator_AndroidSimpleBufferQueue loc_bufq;
     SLDataFormat_PCM format_pcm;
     SLAndroidDataFormat_PCM_EX format_pcm_ex;
+    SLDataSource audioSrc;
+    SLDataSink audioSnk;
+    SLDataLocator_OutputMix loc_outmix;
+    const SLInterfaceID ids[2] = { SL_IID_ANDROIDSIMPLEBUFFERQUEUE, SL_IID_VOLUME };
+    const SLboolean req[2] = { SL_BOOLEAN_TRUE, SL_BOOLEAN_FALSE };
     SLresult result;
     int i;
 
@@ -442,7 +451,8 @@ openslES_CreatePCMPlayer(_THIS)
           this->spec.channels, (this->spec.format & 0x1000) ? "BE" : "LE", this->spec.samples);
 
     /* configure audio source */
-    SLDataLocator_AndroidSimpleBufferQueue loc_bufq = { SL_DATALOCATOR_ANDROIDSIMPLEBUFFERQUEUE, NUM_BUFFERS };
+    loc_bufq.locatorType = SL_DATALOCATOR_ANDROIDSIMPLEBUFFERQUEUE;
+    loc_bufq.numBuffers = NUM_BUFFERS;
 
     format_pcm.formatType    = SL_DATAFORMAT_PCM;
     format_pcm.numChannels   = this->spec.channels;
@@ -501,23 +511,16 @@ openslES_CreatePCMPlayer(_THIS)
         format_pcm_ex.representation = SL_ANDROID_PCM_REPRESENTATION_FLOAT;
     }
 
-    SLDataSource audioSrc = { &loc_bufq, SDL_AUDIO_ISFLOAT(this->spec.format) ? (void*)&format_pcm_ex : (void*)&format_pcm };
+    audioSrc.pLocator = &loc_bufq;
+    audioSrc.pFormat = SDL_AUDIO_ISFLOAT(this->spec.format) ? (void*)&format_pcm_ex : (void*)&format_pcm;
 
     /* configure audio sink */
-    SLDataLocator_OutputMix loc_outmix = { SL_DATALOCATOR_OUTPUTMIX, outputMixObject };
-    SLDataSink audioSnk = { &loc_outmix, NULL };
+    loc_outmix.locatorType = SL_DATALOCATOR_OUTPUTMIX;
+    loc_outmix.outputMix = outputMixObject;
+    audioSnk.pLocator = &loc_outmix;
+    audioSnk.pFormat = NULL;
 
     /* create audio player */
-    const SLInterfaceID ids[2] = {
-        SL_IID_ANDROIDSIMPLEBUFFERQUEUE,
-        SL_IID_VOLUME
-    };
-
-    const SLboolean req[2] = {
-        SL_BOOLEAN_TRUE,
-        SL_BOOLEAN_FALSE,
-    };
-
     result = (*engineEngine)->CreateAudioPlayer(engineEngine, &bqPlayerObject, &audioSrc, &audioSnk, 2, ids, req);
     if (SL_RESULT_SUCCESS != result) {
         LOGE("CreateAudioPlayer failed: %d", result);
@@ -590,7 +593,6 @@ openslES_CreatePCMPlayer(_THIS)
     return 0;
 
 failed:
-
     return -1;
 }
 
```

**Comment by mingmoe** [comment]
> Can't you do a make -k or some equivalent of it so that we can see all errors?
As you might have guessed, I'm doing this blindly for now i.e. no testing at all..

I'm sorry that. But now this patch works.

Thanks a log. Hope to submit to main as soon as possible.

**Comment by sezero** [comment]
OK, patch is applied as https://github.com/libsdl-org/SDL/commit/8c51cae7849dbd86bb62f3ebd444a527e56e0c4d

Please make sure to test functionality, especially OpenSLES where the changes
were most hence the possibility of mistakes.

**Comment by madebr** [comment]
FYI, I accidentally bumped the android ndk version on CI in https://github.com/libsdl-org/SDL/commit/6fa7d62408024e8de64547e33bbc7fbf25ad59ec
Looks like the builds succeed atm.
