### ISSUE TITLE
Game controller mappings broken on PS2, PSP and Vita

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#6151]
The GUIDs have changed for these platforms, need to update the mappings

**Comment by slouken** [comment]
Fixed!

**Comment by fjtrujy** [comment]
Hello @slouken ,

I have been testing your latest changes, which are still not working.
We have this piece of code, that belongs to the OpenSupaplex game, that worked perfectly in previous SDL releases.
https://github.com/sergiou87/open-supaplex/blob/master/src/sdl2/controller.c#L32-L59

```c
SDL_GameController *getGameController()
{
    // The game controller is not valid anymore, invalidate.
    if (sCurrentGameControllerIndex != -1
        && SDL_IsGameController(sCurrentGameControllerIndex) == 0)
    {
        sCurrentGameController = NULL;
    }

    if (sCurrentGameController != NULL)
    {
        return sCurrentGameController;
    }

    int numberOfJoysticks = SDL_NumJoysticks();

    for (int i = 0; i < numberOfJoysticks; ++i)
    {
        if (SDL_IsGameController(i))
        {
            sCurrentGameController = SDL_GameControllerOpen(i);
            sCurrentGameControllerIndex = i;
            break;
        }
    }

    return sCurrentGameController;
}
```

In this piece of code `sCurrentGameController` is currently returning `NULL`.

Pinging as well @sergiou87 , because he is the owner of OpenSupaplex

Cheers

**Comment by fjtrujy** [comment]
Actually also added the output of the test `testgamecontroller`, which was working also before.

```
INFO: Joystick 0: PS2 Controller (guid 000087ed50533220436f6e74726f6c00, VID 0x0000, PID 0x0000, player index = -1)
INFO: Joystick 1: PS2 Controller (guid 000087ed50533220436f6e74726f6c00, VID 0x0000, PID 0x0000, player index = -1)
INFO: Joystick 2: PS2 Controller (guid 000087ed50533220436f6e74726f6c00, VID 0x0000, PID 0x0000, player index = -1)
INFO: Joystick 3: PS2 Controller (guid 000087ed50533220436f6e74726f6c00, VID 0x0000, PID 0x0000, player index = -1)
INFO: Joystick 4: PS2 Controller (guid 000087ed50533220436f6e74726f6c00, VID 0x0000, PID 0x0000, player index = -1)
INFO: Joystick 5: PS2 Controller (guid 000087ed50533220436f6e74726f6c00, VID 0x0000, PID 0x0000, player index = -1)
INFO: Joystick 6: PS2 Controller (guid 000087ed50533220436f6e74726f6c00, VID 0x0000, PID 0x0000, player index = -1)
INFO: Joystick 7: PS2 Controller (guid 000087ed50533220436f6e74726f6c00, VID 0x0000, PID 0x0000, player index = -1)
INFO: There are 0 game controller(s) attached (8 joystick(s))
```

**Comment by slouken** [comment]
It looks like that should match this mapping:
    "0000000050533220436f6e74726f6c00,PS2 Controller,crc:87ed,a:b14,b:b13,back:b0,dpdown:b6,dpleft:b7,dpright:b5,dpup:b4,leftshoulder:b10,leftstick:b1,lefttrigger:b8,leftx:a0,lefty:a1,rightshoulder:b11,rightstick:b2,righttrigger:b9,rightx:a2,righty:a3,start:b3,x:b15,y:b12,",

Can someone with a test environment debug into SDL_PrivateGetControllerMappingForGUID() and see what's happening there?

**Comment by fjtrujy** [comment]
I found the issue, it is in the `SDL_gamecontrollerdb`, I'm creating the PR

**Comment by fjtrujy** [comment]
I have tested both applications, `OpenSupaplex` and the `testgamecontroller`, now it is working fine

https://github.com/libsdl-org/SDL/pull/6201

**Comment by fjtrujy** [comment]
> It looks like that should match this mapping: "0000000050533220436f6e74726f6c00,PS2 Controller,crc:87ed,a:b14,b:b13,back:b0,dpdown:b6,dpleft:b7,dpright:b5,dpup:b4,leftshoulder:b10,leftstick:b1,lefttrigger:b8,leftx:a0,lefty:a1,rightshoulder:b11,rightstick:b2,righttrigger:b9,rightx:a2,righty:a3,start:b3,x:b15,y:b12,",
> 
> Can someone with a test environment debug into SDL_PrivateGetControllerMappingForGUID() and see what's happening there?

Is not exactly the same id
`0000000050533220436f6e74726f6c00`
`000087ed50533220436f6e74726f6c00`

**Comment by slouken** [comment]
It is not intended to be the same ID. It should have 0 in the first 4 bytes, and a matching CRC field. Can you debug `SDL_PrivateGetControllerMappingForGUID()` and check the CRC logic there?

**Comment by fjtrujy** [comment]
> SDL_PrivateGetControllerMappingForGUID

Yes, let me check

**Comment by fjtrujy** [comment]
@slouken 
This is the best that I can do (having in mind that we don't have gdb for PS2)

```c
/*
 * Helper function to scan the mappings database for a controller with the specified GUID
 */
static ControllerMapping_t *SDL_PrivateGetControllerMappingForGUID(SDL_JoystickGUID guid)
{
    ControllerMapping_t *mapping;
    Uint16 vendor, product, crc;

    SDL_GetJoystickGUIDInfo(guid, &vendor, &product, NULL, &crc);
    if (crc) {  // <------------ ENTERS HERE
        /* First check for exact CRC matching */ 
        mapping = SDL_PrivateMatchControllerMappingForGUID(guid, SDL_TRUE, SDL_TRUE);
        if (mapping) {  // <----------- DOESN'T ENTER HERE
            return mapping;
        }
    }

    /* Now check for a mapping without CRC */
    mapping = SDL_PrivateMatchControllerMappingForGUID(guid, SDL_FALSE, SDL_TRUE);
    if (mapping) { // <----------- DOESN'T ENTER HERE
        return mapping;
    }

    if (vendor && product) { // <----------- DOESN'T ENTER HERE
        /* Try again, ignoring the version */
        if (crc) {
            mapping = SDL_PrivateMatchControllerMappingForGUID(guid, SDL_TRUE, SDL_FALSE);
            if (mapping) {
                return mapping;
            }
        }

        mapping = SDL_PrivateMatchControllerMappingForGUID(guid, SDL_FALSE, SDL_FALSE);
        if (mapping) {
            return mapping;
        }
    }

#if SDL_JOYSTICK_XINPUT
    if (SDL_IsJoystickXInput(guid)) {
        /* This is an XInput device */
        return s_pXInputMapping;
    }
#endif
    if (!mapping) { // <----------- ENTERS HERE
        if (SDL_IsJoystickHIDAPI(guid)) {
            mapping = SDL_CreateMappingForHIDAPIController(guid);
        } else if (SDL_IsJoystickRAWINPUT(guid)) {
            mapping = SDL_CreateMappingForRAWINPUTController(guid);
        } else if (SDL_IsJoystickWGI(guid)) {
            mapping = SDL_CreateMappingForWGIController(guid);
        } else if (SDL_IsJoystickVirtual(guid)) {
            /* We'll pick up a robust mapping in VIRTUAL_JoystickGetGamepadMapping */
#ifdef __ANDROID__
        } else {
            mapping = SDL_CreateMappingForAndroidController(guid);
#endif
        }
    }
    return mapping;
}
```

Cheers

**Comment by slouken** [comment]
Can you look at the first call to `SDL_PrivateMatchControllerMappingForGUID()`? It should get the CRC, then set the CRC to 0 in the guid, then pull out the CRC field from the mapping, and then successfully compare them. Can you print out the CRC that comes from the GUID, and the one that comes from the mapping field?

It's possible that SDL_strtol() isn't working right or there's some assumption about endianness that we're running into here.

**Comment by fjtrujy** [comment]
> Can you look at the first call to `SDL_PrivateMatchControllerMappingForGUID()`? It should get the CRC, then set the CRC to 0 in the guid, then pull out the CRC field from the mapping, and then successfully compare them. Can you print out the CRC that comes from the GUID, and the one that comes from the mapping field?
> 
> It's possible that SDL_strtol() isn't working right or there's some assumption about endianness that we're running into here.

This is where I have put the `printf` messages

```c
static ControllerMapping_t *SDL_PrivateMatchControllerMappingForGUID(SDL_JoystickGUID guid, SDL_bool match_crc, SDL_bool match_version)
{
    ControllerMapping_t *mapping;
    Uint16 crc = 0;

    if (match_crc) {
        SDL_GetJoystickGUIDInfo(guid, NULL, NULL, NULL, &crc);
        printf("crc = %x\n", crc); // <------------------------------ PRINTF 
    }

    /* Clear the CRC from the GUID for matching, the mappings never include it in the GUID */
    SDL_SetJoystickGUIDCRC(&guid, 0);

    if (!match_version) {
        SDL_SetJoystickGUIDVersion(&guid, 0);
    }

    for (mapping = s_pSupportedControllers; mapping; mapping = mapping->next) {
        SDL_JoystickGUID mapping_guid;

        SDL_memcpy(&mapping_guid, &mapping->guid, sizeof(mapping_guid));
        if (!match_version) {
            SDL_SetJoystickGUIDVersion(&mapping_guid, 0);
        }

        if (SDL_memcmp(&guid, &mapping_guid, sizeof(guid)) == 0) {
            Uint16 mapping_crc = 0;
            const char *crc_string = SDL_strstr(mapping->mapping, SDL_CONTROLLER_CRC_FIELD);
            printf("crc_string = %s\n", crc_string); // <------------------------------ PRINTF
            if (crc_string) {
                mapping_crc = (Uint16)SDL_strtol(crc_string + SDL_CONTROLLER_CRC_FIELD_SIZE, NULL, 16); 
                printf("mapping_crc = %x\n", mapping_crc); // <------------------------------ PRINTF
            }
            if (crc == mapping_crc) {
                return mapping;
            }
        }
    }
    return NULL;
}
```

And the vales are:
```
crc = ed87
crc_string = crc:87ed,a:b14,b:b13,back:b0,dpdown:b6,dpleft:b7,dpright:b5,dpup:b4,leftshoulder:b10,leftstick:b1,lefttrigger:b8,leftx:a0,lefty:a1,rightshoulder:b11,rightstick:b2,righttrigger:b9,rightx:a2,righty:a3,start:b3,x:b15,y:b12,
mapping_crc = 87ed
```

Look to be some assumption wrong about endianness.

**Comment by fjtrujy** [comment]
> I know what the problem is. The program I used to generate the mapping CRC didn't byte swap it when it was written out. I think just swapping the CRC in the mappings will work.

Ok, let me know when I can try to test

**Comment by slouken** [comment]
Try the latest code including https://github.com/libsdl-org/SDL/commit/a0f169603d6fa94bebf4bb963904e1c89333af25

**Comment by fjtrujy** [comment]
> Try the latest code including [a0f1696](https://github.com/libsdl-org/SDL/commit/a0f169603d6fa94bebf4bb963904e1c89333af25)

I have tested it, with the `OpenSupaplex` and the `testgamecontroller` and in both scenarios is working properly for `PS2`.

Thanks for your help!

**Comment by ccawley2011** [comment]
One additional question: Would it be worth providing an implementation of `PS2_GetGamepadMapping` instead of relying on the gamecontrollerdb for mappings in the PS2 port?

**Comment by slouken** [comment]
> I have tested it, with the `OpenSupaplex` and the `testgamecontroller` and in both scenarios is working properly for `PS2`.

Great, thanks!

**Comment by slouken** [comment]
> One additional question: Would it be worth providing an implementation of `PS2_GetGamepadMapping` instead of relying on the gamecontrollerdb for mappings in the PS2 port?

No, the GetGamepadMapping code is really for getting mappings that are done heuristically based on OS-specific information. For mappings of a known set of controllers, having them in SDL_gamecontrollerdb.h is fine.

There are some cases where having the mapping available without the device is useful, so having the mapping in advance is preferrable where possible.
