### ISSUE TITLE
White textures on 32-bit laptop (SDL2)

### ISSUE THREAD

**Issue by lumidify** [libsdl-org/SDL#7194]
While trying to run The Legend of Edgar (https://github.com/riksweeney/edgar) on an old 32-bit Laptop, the screen turns completely white shortly after starting the game. In certain cases, not the entire screen turns white, but at least it seems as if all textures turn white. This happens both on a laptop with "AMD RV250/M9 GL [Mobility FireGL 9000/Radeon 9000]" as its graphics card, and another one with "Intel 82852/855GM Integrated Graphics" (both using a Pentium M processor, but slightly different models). This is on antiX Linux 21.

I first tried to find a bug in The Legend of Edgar, but that didn't lead anywhere, so I started looking at the SDL source code. With the help of `git bisect` and the friendly folks in the SDL IRC channel, I determined that this issue seems to have started occurring with the following commit: https://github.com/libsdl-org/SDL/commit/d04e55240e1949c521e609766f78a46186187808#diff-4956a04b2a5178a1ab45e6567ebbd365a956893ddc64227a9f14d1ea211a634dR956

Specifically, line 956 of `src/render/opengl/SDL_render_gl.c` (linked above) seems to be the issue, as it works properly if I just remove that check so the inside of the if statement always runs. After looking a bit further, I found a line in `GL_CreateTexture` which sets `renderdata->drawstate.texture` to `NULL`, but does not modify `renderdata->drawstate.texturing`. This line still exists in release 2.6.2 and the branch "SDL2": https://github.com/libsdl-org/SDL/blob/release-2.26.2/src/render/opengl/SDL_render_gl.c#L467 https://github.com/libsdl-org/SDL/blob/SDL2/src/render/opengl/SDL_render_gl.c#L460. If I add a line `renderdata->drawstate.texturing = SDL_FALSE;` below that line, everything appears to work, or at least I haven't been able to trigger the issue anymore (to get the version from the SDL2 branch to work without crashing, I have to use `-DSDL_SSE3=OFF` in the `cmake` command, but that's a different matter).

Since I don't know anything about the low-level details here: Does this make sense, or am I barking up the wrong tree? And if so, why would it only occur on these old machines?

**Comment by slouken** [comment]
@icculus, can you look at this for the next release?

**Comment by icculus** [comment]
I pushed a fix to this (@lumidify is correct, we trash the `texturing` state when creating a texture), but I'm honestly surprised this isn't happening everywhere if that's the problem.

Anyhow, please retest with the latest in the SDL2 branch of SDL, if you can, and let's see if it solves the problem.

**Comment by icculus** [comment]
I'm assuming that b24d6bd59a86059383742b9b31ac955f8f4a49c4 fixed this; if you get a chance to retest and it's still broken, let me know and I'll reopen the issue!

**Comment by lumidify** [comment]
Thanks for pushing the fix! I haven't been able to test it yet because I need to set up my 32-bit laptop properly again. If I manage to reproduce the issue still, I'll mention that here, but I'm pretty sure it's fixed now.
