### ISSUE TITLE
[MacOS] SDL2 does not support bluetooth headsets when the microphone is active

### ISSUE THREAD

**Issue by OIRNOIR** [libsdl-org/SDL#8192]
When using a bluetooth headphone device, the audio stops when the microphone is activated due to the headphones switching to a lower bitrate for bidirectional communications because bluetooth

**Comment by OIRNOIR** [comment]
When a headset is connected where the mic is not in use, the bluetooth connection has a high bitrate because data is only going in one direction (from the computer to the audio device). However, when the device is being used as both an input and an output device, the connection is switched to a far lower bitrate to allow for bidirectional transmission (smh bluetooth)

**Comment by icculus** [comment]
I'll verify this, but I think this got fixed by the audio subsystem rewrite.

**Comment by darbyjohnston** [comment]
Hi, I'm seeing the same issue; I created a simple test program with the `preview-3.1.3` tag and it still happens. I'm using `SDL_OpenAudioDeviceStream()` which I assume is part of the audio subsystem rewrite?

**Comment by icculus** [comment]
Interesting: audio is bad if recording when loopwave is started, too, so it's not that the format _changed_ on us.

**Comment by icculus** [comment]
This is just as stupid as using more AudioQueueBuffers. I changed it from 2 to 4 and it works just fine without looking for device property changes.

I'm going to do some testing for latency, and if it's the number of buffers vs the buffer size, and we'll probably be done with this, then.
