### ISSUE TITLE
iOS: Window created with exclusive fullscreen uses wrong orientation in SDL2

### ISSUE THREAD

**Issue by slime73** [libsdl-org/SDL#8200]
After creating a window in exclusive fullscreen with landscape orientation (w > h) in SDL2, it ends up with portrait orientation. I think this might be an SDL2-specific issue (although a fix might be mergeable into SDL3's code as well) because SDL3 is more restrictive with creating fullscreen windows.

This was originally reported over here: https://github.com/love2d/love/issues/1903

I did some debugging a little while ago and it seems that `[SDL_uikitviewcontroller updateKeyboard]` can be called while UIKit reports the view's window property as nil (something to do with how early updateKeyboard is called I guess), which passes a nil UIScreen into UIKit_ComputeViewFrame:
https://github.com/libsdl-org/SDL/blob/365a36386ac18a2636c0d7b9597edb3644df0735/src/video/uikit/SDL_uikitviewcontroller.m#L492-L496

This causes the `fullscreen` boolean in UIKit_ComputeViewFrame's code to be `NO` even though the window is fullscreen, which stops it from hitting the codepath which swaps the width and height: https://github.com/libsdl-org/SDL/blob/266b91d2fd2b3362d1828f8a6b58589bdaa4f75d/src/video/uikit/SDL_uikitvideo.m#L232-L240

I have a small patch to make `updateKeyboard` use the SDL window's stored UIScreen variable instead of accessing the view's window's property for that. It appeared to solve the specific problem described here when I tested it a while ago, although I don't know why the view's window's UIScreen property was nil in the first place. The patch is for SDL3, changing `SDL_UIKitWindowData` to `SDL_WindowData` should make it work in SDL2.

```patch
diff --git a/src/video/uikit/SDL_uikitviewcontroller.m b/src/video/uikit/SDL_uikitviewcontroller.m
--- a/src/video/uikit/SDL_uikitviewcontroller.m
+++ b/src/video/uikit/SDL_uikitviewcontroller.m
@@ -511,12 +511,14 @@ static void SDLCALL SDL_HideHomeIndicatorHintChanged(void *userdata, const char
 
 - (void)updateKeyboard
 {
+    SDL_UIKitWindowData *data = (__bridge SDL_UIKitWindowData *) window->driverdata;
+
     CGAffineTransform t = self.view.transform;
     CGPoint offset = CGPointMake(0.0, 0.0);
 #if TARGET_OS_XR
     CGRect frame = UIKit_ComputeViewFrame(window);
 #else
-    CGRect frame = UIKit_ComputeViewFrame(window, self.view.window.screen);
+    CGRect frame = UIKit_ComputeViewFrame(window, data.uiwindow.screen);
 #endif
 
     if (self.keyboardHeight) {

```

However, there's another apparent fullscreen orientation bug on iOS right now I discovered while testing this problem, which this doesn't fix: #8201

**Comment by slime73** [comment]
After doing some more testing I think there might be multiple overlapping issues causing this specific problem (for example it won't always pick the right fullscreen size to use in CreateWindow in SDL2, because of GetClosestDisplayModeForDisplay's implementation. And working around that doesn't solve it either) - my above patch doesn't really fix things in recent SDL versions. I'm pretty sure it did when I tested it with an older version a month or two ago but maybe I was testing a slightly different setup from now...

**Comment by slouken** [comment]
I just tested testspriteminimal with the latest SDL2 code and it's working fine here. Do you have specific repro steps?
I did run into the flip-flopping orientation bug a while back, so maybe this is fixed now?

**Comment by slouken** [comment]
We're releasing SDL 2.30 soon and haven't heard back, so I'm going ahead and closing this for now. Feel free to add more information and reopen it if you're still having this issue.

**Comment by slime73** [comment]
Yes it's absolutely still reproducible, you just need to modify testspritewindow to create an exclusive fullscreen window instead of a windowed window (add `SDL_WINDOW_FULLSCREEN` to the `SDL_CreateWindowAndRenderer` call). I suspect a lot of people won't be doing much testing during the winter holidays. :)

Applying my patch above - modified to work with SDL2's codebase instead of SDL3's - fixes that issue and then immediately runs into #8201 because the fix for that has not been backported to SDL2.

**Comment by slouken** [comment]
Thanks for the feedback. Those fixes have been cherry-picked to SDL2, and both testrendercopyex --fullscreen and testspriteminimal with SDL_WINDOW_FULLSCREEN is working well here. Are you still running into other related issues?

**Comment by slouken** [comment]
I'm going to go ahead and close this. Please reopen this if the issues you reported aren't fixed, and feel free to open new issues if you find other things are broken.

Thanks!
