### ISSUE TITLE
Multi-stream sound will cause assertion failure

### ISSUE THREAD

**Issue by kanjitalk755** [libsdl-org/SDL#8226]
The source below is a sample that plays two streams simultaneously.

```C
#include <SDL.h>
#include <stdlib.h>

int main(int argc, char *argv[]) {
	if (SDL_Init(SDL_INIT_AUDIO)) exit(1);
	atexit(SDL_Quit);
	static struct {
		SDL_AudioStream *stream;
		SDL_AudioSpec spec;
		Uint8 *buf;
		Uint32 len;
	} wav1, wav2;
	if (SDL_LoadWAV("sample1.wav", &wav1.spec, &wav1.buf, &wav1.len)) exit(1);
	if (SDL_LoadWAV("sample2.wav", &wav2.spec, &wav2.buf, &wav2.len)) exit(1);
	wav1.stream = SDL_OpenAudioDeviceStream(SDL_AUDIO_DEVICE_DEFAULT_OUTPUT, &wav1.spec, NULL, NULL);
	wav2.stream = SDL_OpenAudioDeviceStream(SDL_AUDIO_DEVICE_DEFAULT_OUTPUT, &wav2.spec, NULL, NULL);
	if (wav1.stream == NULL || wav2.stream == NULL) exit(1);
	SDL_ResumeAudioDevice(SDL_GetAudioStreamDevice(wav1.stream));
	SDL_ResumeAudioDevice(SDL_GetAudioStreamDevice(wav2.stream));
	SDL_PutAudioStreamData(wav1.stream, wav1.buf, wav1.len);
	SDL_PutAudioStreamData(wav2.stream, wav2.buf, wav2.len);
	for (int quit = 0; !quit;) {
		SDL_Event e;
		while (SDL_PollEvent(&e)) {
			switch (e.type) {
				case SDL_EVENT_MOUSE_BUTTON_DOWN:
				case SDL_EVENT_QUIT:
					quit = 1;
					break;
			}
		}
		if (!SDL_GetAudioStreamAvailable(wav1.stream)) break;
		if (!SDL_GetAudioStreamAvailable(wav2.stream)) break;
	}
	return 0;
}
```

@icculus The first commit that reproduces the playback error is fd7cd91dc.

I confirmed only on macOS.

**Comment by icculus** [comment]
I actually fixed this bug in #8213, which will be merging shortly (maybe today?).

**Comment by icculus** [comment]
(The specific fix is this line:

https://github.com/libsdl-org/SDL/pull/8213/commits/6b72728b7defd2c856f8bf4c2f42e5d10b13853f#diff-5f0f1ef0932faa81f14a72dbbe1fee047b928d677f7ff885fed4ec6bf576df16L745

`buffer_size` doesn't silence the whole buffer, it needed to be `work_buffer_size`.)

**Comment by icculus** [comment]
This should be fixed in revision control now; let me know if it is still broken for your sample*.wav files, though!

**Comment by kanjitalk755** [comment]
With the same source, I can no longer play with the following assertion.

```
Assertion failure at SDL_OutputAudioThreadIterate (***/SDL/src/audio/SDL_audio.c:870), triggered 1 time:
  '(((stream->dst_spec).format == (outspec).format) && ((stream->dst_spec).channels == (outspec).channels) && ((stream->dst_spec).freq == (outspec).freq))'
```

The first commit where this issue reproduces is 54125c140.

**Comment by icculus** [comment]
I'll debug this in the morning.

**Comment by icculus** [comment]
The assert is fixed in a5175e5ed04eb4b4ad1e40dd55be51d7f684af30. Thanks!

**Comment by kanjitalk755** [comment]
Unfortunately, the issue is not fixed.

In UpdateAudioStreamFormatsLogical(), the format of the stream initially bound to the logical device may not be SDL_AUDIO_F32.
But all formats must be SDL_AUDIO_F32 when mixing.

**Comment by slouken** [comment]
Have you tried the latest code? I believe this was addressed today.

**Comment by kanjitalk755** [comment]
Yes. I tried 4db2b968a.

**Comment by icculus** [comment]
Can you zip up the two sample
.wav files you're using and attach them here? I'll see if I can reproduce with your data.

**Comment by kanjitalk755** [comment]
You can reproduce the issue with SDL/test/sample.wav and its copy.

**Comment by icculus** [comment]
This is fixed (again!)

**Comment by kanjitalk755** [comment]
Yes, confirmed. Thanks.

**Comment by MrJokerBoy** [comment]
Hello, whether the current problem has been fixed, I also encountered the same problem.
