### ISSUE TITLE
SDL3 cmake cross-compile broken

### ISSUE THREAD

**Issue by rofl0r** [libsdl-org/SDL#9349]
i'm trying to compile 'main' branch for PSP in order to port my feature, however ...

SDL_DetectCMakePlatform() correctly detects the platform i compile for and sets SDL_CMAKE_PLATFORM psp, however it then completely ignores SDL_CMAKE_PLATFORM and instead uses UNIX variable to determine that i build for UNIX, which is probably set because the host is unix.

**Comment by rofl0r** [comment]
the official toolchain file i used is https://github.com/pspdev/pspsdk/blob/5ccc22c19fd26c1259646081aa2878cefd783db4/src/base/pspdev.cmake

**Comment by madebr** [comment]
I applied this debug patch:
```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -97,6 +97,7 @@ list(APPEND CMAKE_REQUIRED_LINK_OPTIONS ${SDL_CHECK_REQUIRED_LINK_OPTIONS})
 
 # Get the platform
 SDL_DetectCMakePlatform()
+message(FATAL_ERROR "SDL_CMAKE_PLATFORM: \"${SDL_CMAKE_PLATFORM}\" UNIX:\"${UNIX}\"")
 
 # Don't mistake macOS for unix
 if(UNIX AND NOT ANDROID AND NOT APPLE AND NOT RISCOS)

```
and got this output on the `docker.io/pspdev/pspdev:latest` container:
```
CMake Error at CMakeLists.txt:100 (message):
  SDL_CMAKE_PLATFORM: "psp" UNIX:""
```
[psp's cmake toolchain](https://github.com/pspdev/pspsdk/blob/5ccc22c19fd26c1259646081aa2878cefd783db4/src/base/pspdev.cmake) correctly does not set the `UNIX` variable so I think wer're fine.

Can you verify my results?

**Comment by rofl0r** [comment]
SDL_CMAKE_PLATFORM: "psp" UNIX:"1"

**Comment by madebr** [comment]
What is your complete configuration command?

**Comment by rofl0r** [comment]
https://0x0.st/XsKd.sh

**Comment by madebr** [comment]
That looks reasonable.
Are you building this in a docker (if you aren't, can you try?)?
If you aren't building in a docker, what os are you using? And are you using your system's cmake version?

**Comment by rofl0r** [comment]
i use my own OS sabotage linux, not in docker (don't even have a go compiler to compile docker), and yes, system cmake, version 3.20.3

**Comment by rofl0r** [comment]
please don't just bump the required CMake version, i just recompiled it and it took 40 minutes, and it's a PITA to get it building against musl libc to begin with. why not simply use  SDL_CMAKE_PLATFORM consistently when checking for the platform properties ?

**Comment by madebr** [comment]
> please don't just bump the required CMake version, i just recompiled it and it took 40 minutes, and it's a PITA to get it building against musl libc to begin with. 

Don't worry, that's not on the table. (yet)

Just kidding about the yet.

> why not simply use SDL_CMAKE_PLATFORM consistently when checking for the platform properties ?

A combination about being conservative, and UNIX grouping multiple operating systems (Linux, *BSD, GNU, ...). I introduced `SDL_CMAKE_PLATFORM` primarily for creating binary SDL3 packages, not for the detection phase.

**Comment by madebr** [comment]
What is the output of 
```
cmake . --trace-expand 2>&1 | grep UNIX
```
I'm curious where `UNIX` is being defined for you.

**Comment by rofl0r** [comment]
```
~/tmp/SDL/build3[main*]$ cmake . --trace-expand 2>&1 | grep UNIX
/home/rofl/tmp/SDL/CMakeLists.txt(3):  SET(UNIX FALSE )
/opt/cmake/share/cmake-3.20/Modules/CMakeSystemSpecificInformation.cmake(15):  set(UNIX )
/opt/cmake/share/cmake-3.20/Modules/CMakeGenericSystem.cmake(168):  if(CMAKE_HOST_UNIX )
/opt/cmake/share/cmake-3.20/Modules/Platform/UnixPaths.cmake(10):  if(__UNIX_PATHS_INCLUDED )
/opt/cmake/share/cmake-3.20/Modules/Platform/UnixPaths.cmake(13):  set(__UNIX_PATHS_INCLUDED 1 )
/opt/cmake/share/cmake-3.20/Modules/Platform/UnixPaths.cmake(15):  set(UNIX 1 )
/opt/cmake/share/cmake-3.20/Modules/CMakeCInformation.cmake(15):  if(UNIX )
```
does that help ?

**Comment by rofl0r** [comment]
the first line is from a hack i tried, i just removed it, still UNIX is 1

**Comment by madebr** [comment]
The fact it's including `Platform/UnixPaths.cmake` shows your cmake version is handling the cmake toolchain badly.
Can you try the binaries at https://cmake.org/files/v3.20/? I'm not sure they work on musl.

**Comment by rofl0r** [comment]
yeah, they don't work  here, sry

> shows your cmake version is handling the cmake toolchain badly.

you mean the psp toolchain file ?

**Comment by madebr** [comment]
Let's compare outputs.
I created this dummy cmake project:
```cmake
cmake_minimum_required(VERSION 3.16)
project(dummy C)
```
And got the following output when running `cmake -S /src -B /build -DCMAKE_TOOLCHAIN_FILE=$PSPDEV/psp/share/pspdev.cmake --trace-expand --fresh >psp.log 2>&1`: [psp.log](https://github.com/libsdl-org/SDL/files/14736894/psp.log)
This is using CMake 3.27.8 (installed on the psp docker image)

**Comment by rofl0r** [comment]
Running with expanded trace output on.
CMake Error: Unknown argument --fresh
CMake Error: Run 'cmake --help' for all supported options.


trying without --fresh

**Comment by rofl0r** [comment]
https://0x0.st/XsPK.log

**Comment by rofl0r** [comment]
fixed the /build error: https://0x0.st/XsPP.log

**Comment by madebr** [comment]
Yeah, I am running these commands in a docker container.
So I don't really care about the folder structure.

**Comment by madebr** [comment]
Your log looks fine.

I think the following happened:
- you ran cmake without `-DCMAKE_TOOLCHAIN_FILE=...` (or a wrong command)
- You later realized you forgot to add `-DCMAKE_TOOLCHAIN_FILE` and added it
- You see `UNIX` is defined, because CMake will keep using the original (default) cmake toolchain file

To test this theory:
- Open `CMakeCache.txt` in your build folder, and check whether the `CMAKE_*` variables point to your system compiler, or to executables of psp.
- Configure your project in a new build project, with only `-DCMAKE_TOOLCHAIN_FILE=$PSPDEV/psp/share/pspdev.cmake`.

**Comment by rofl0r** [comment]
here's a partial trace how we got to unixpath.cmake
/opt/cmake/share/cmake-3.20/Modules/CMakeSystemSpecificInformation.cmake(24):
 set(CMAKE_SYSTEM_INFO_FILE Platform/Linux )
/opt/cmake/share/cmake-3.20/Modules/CMakeSystemSpecificInformation.cmake(26):
 include(Platform/Linux OPTIONAL RESULT_VARIABLE _INCLUDED_SYSTEM_INFO_FILE )

/opt/cmake/share/cmake-3.20/Modules/Platform/Linux.cmake(52):  include(Platform/UnixPaths )

**Comment by rofl0r** [comment]
first occurence of CMAKE_ in that file is //Path to a program.
CMAKE_ADDR2LINE:FILEPATH=~/toolchains/mipsallegrexel-psp-elf/bin/psp-addr2line

**Comment by rofl0r** [comment]
but you are right, making a new build directory magically lets the UNIX disappear

**Comment by madebr** [comment]
That's something with CMake: you can't change `CMAKE_TOOLCHAIN_FILE` after the first configuration. Even if you `CTRL+C`'d it.

When you pass another toolchain file, the following warning appears:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_TOOLCHAIN_FILE


```

**Comment by slouken** [comment]
I'm glad you guys figured it out. Thanks for the troubleshooting @madebr!

**Comment by rofl0r** [comment]
> That's something with CMake

wow... that's even worse than the 5000 lines of code it executes to determine the compiler version because the cmake language is too restricted...

is that warning supposed to be printed on stdout ? because it was not shown

**Comment by madebr** [comment]
> is that warning supposed to be printed on stdout ? because it was not shown

It shows on stderr every time you configure an already-configured build folder with a different `CMAKE_TOOLCHAIN_FILE` variable.

**Comment by rofl0r** [comment]
well, for some reason it accepted the toolchain file and wrote the correct values into cmakecache, but then it also must've had some other remains that made it think to include unixpath.cmake

**Comment by madebr** [comment]
I don't know where CMake stores everything, but there's also `CMakeFiles/3.20.3/CMakeCCompiler.cmake` and `CMakeFiles/3.20.3/CMakeSystem.cmake`.
Those files are generated only once.

**Comment by rofl0r** [comment]
but thanks, lesson learned. if cmake makes trouble, delete dir and retry. similar how you unplug and replug HP printers..

**Comment by madebr** [comment]
Who buys HP printers these days?

I'm glad we could help you.

**Comment by Strahinja** [comment]
> That's something with CMake: you can't change `CMAKE_TOOLCHAIN_FILE` after the first configuration. Even if you `CTRL+C`'d it.
> 
> When you pass another toolchain file, the following warning appears:
> 
> ```
> CMake Warning:
>   Manually-specified variables were not used by the project:
> 
>     CMAKE_TOOLCHAIN_FILE
> ```

Note that currently under MSYS2, with
```
$ cat /proc/version
MINGW64_NT-10.0-19045 version 3.6.4-23a25d49.x86_64 (runneradmin@runnervm51nrn) (gcc version 15.1.0 (GCC) ) 2025-07-16 16:15 UTC
$ cmake --version
cmake version 4.0.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
using the switch `--toolchain path/to/toolchain-file.cmake` instead of `-DCMAKE_TOOLCHAIN_FILE=path/to/toolchain-file.cmake` successfully overwrites the build files instead of erroring out.
