### ISSUE TITLE
Vulkan renderer backend crashing frequently, possibly due to SDL_SetRenderTarget?

### ISSUE THREAD

**Issue by ShockSlayer** [libsdl-org/SDL#9385]
This issue is a little difficult to provide exact reproduction steps for, so my aim here is to provide as much information as I can, and hope for the best.

I'm currently trying out the 3.1.0 preview. My game engine currently sets the hint to use the vulkan backend, initializes the renderer and a window, loads a 4096x4096 texture atlas, then creates a "camera" texture to render to. It then does all of its game/debug-relevant drawing through SDL_RenderGeometry, before switching the render target back to the window, to render the completed camera texture to the window using SDL_RenderTexture. Additionally, I'm using Dear ImGui, the rendering function of which I would call shortly after this before finally presenting the window.

This works completely fine when using the openGL and direct3d12 backends, but I get "glitchy behavior" when using the vulkan backend, and frequently get the same access violation error in the same place. By "glitchy behavior," I have textures flickering, turning white, or disappearing entirely. This doesn't always happen though; sometimes I'll get an access violation error nearly instantly on starting the game, other times I have to toggle my debug primitives (of which there are many) on and off a few times.

This seems to happen when I'm calling SDL_SetRenderTarget to return the target to the window; the call stack gets as far as VULKAN_DrawPrimitives before the exception is thrown somewhere in nvoglv64.dll.

ERROR: vkQueueSubmit(): VK_ERROR_DEVICE_LOST
Exception thrown at 0x00007FFDEFE10F65 (nvoglv64.dll) in application_name.exe: 0xC0000005: Access violation writing location 0x0000000000000000.

This is before the Dear ImGui render call, or the SDL_RenderTexture call, but I didn't want to leave that out in case it's somehow relevant.

**Comment by slouken** [comment]
Can you turn on the Vulkan debug validation layer? That will probably show some kind of issue before the crash.

**Comment by ShockSlayer** [comment]
I've installed the Vulkan SDK and set SDL_HINT_RENDER_VULKAN_DEBUG to 1. I can tell it's working because it slows down performance to a unusual crawl in an area with a lot of geometry. Unfortunately, with the validation layers active, I'm unable to reproduce the bug. Comes right back though if I disable them.

That said, while the application is running, I get several of these, all otherwise identical except for the address: 

VUID-vkDestroyBuffer-buffer-00922(ERROR / SPEC): msgNum: -464217071 - Validation Error: [ VUID-vkDestroyBuffer-buffer-00922 ] | MessageID = 0xe4549c11 | vkDestroyBuffer():  can't be called on VkBuffer 0xf76e8500000722e0[] that is currently in use by VkCommandBuffer 0x1940dd01390[]. The Vulkan spec states: All submitted commands that refer to buffer, either directly or via a VkBufferView, must have completed execution (https://vulkan.lunarg.com/doc/view/1.3.280.0/windows/1.3-extensions/vkspec.html#VUID-vkDestroyBuffer-buffer-00922)

Hopefully that helps?

**Comment by slouken** [comment]
This is probably the issue. @danginsburg, can you take a look?

**Comment by danginsburg** [comment]
> This is probably the issue. @danginsburg, can you take a look?

I'll do what I can.  If a reproducer executable could be provided that would be fantastic.  Short of that, it might help me reverse what is going on if you use `gfxrecon` (in the Vulkan SDK) or `renderdoc` to take a capture.  It would be much better if I can reproduce it myself though, otherwise it'll be a fair bit of guess work.

**Comment by slouken** [comment]
I think the issue here is that we're switching from using the texture as a render target to a render source without the rendering being complete. Am I mis-reading the validation error above?

**Comment by danginsburg** [comment]
It could be.  To me it looks like we are deleting a buffer before the fence associated with its submit completes.

**Comment by danginsburg** [comment]
I tried reproducing this, but was unable to.  I found some synchronization validation issues that I fixed in https://github.com/libsdl-org/SDL/pull/9390, but it is very unlikely that will fix this bug.  It would really help if I could get some more reproducer information.

**Comment by danginsburg** [comment]
One thing that might be a decent clue @ShockSlayer is if you set a breakpoint on:

```    
    /* If we've used up all the upload buffers, we need to issue the batch */
    if (rendererData->currentUploadBuffer[rendererData->currentCommandBufferIndex] == SDL_VULKAN_NUM_UPLOAD_BUFFERS) {
        VULKAN_IssueBatch(rendererData);
    }
```

in `VULKAN_UpdateTextureInternal`.  If you are hitting that condition (`Vulkan_IssueBatch`), I wonder if we have some bug where the buffer is being deleted before consumption.  I'm having a hard time seeing how that would happen since that path wait idles the GPU.  However, if it is that, maybe try bumping SDL_VULKAN_NUM_UPLOAD_BUFFERS until you stop hitting that condition and if that fixes it at least we know the problem is there.

**Comment by ShockSlayer** [comment]
I set a breakpoint, but I never hit `VULKAN_IssueBatch` before the crash. I tried changing `SDL_VULKAN_NUM_UPLOAD_BUFFERS` to a higher number, but this did not seem to have any effect.

Occasionally I will get an access violation in `VULKAN_SetDrawState` when calling `vkCmdBindPipeline`.

After updating, unfortunately the issue does not go away. Instead, this same kind of error now sometimes happens after calling `vkCmdBindDescriptorSets` in `VULKAN_SetDrawState`.

The only other information I have is that I seem to get crashes faster and more frequently in release mode over debug mode. Having the validation layers on still prevents the crash, and I still get the same error in the output window as mentioned above.

I'm willing to run any other tests like this that may be useful. I will see if I can replicate this issue outside of my program using a similar setup so that someone else can run this, but this may take a little time for me to get to.

**Comment by danginsburg** [comment]
I'll definitely get this fixed if I can figure out how to repro.  If you able to provide a repro privately but not publicly, let me know and we can figure something out.

**Comment by ShockSlayer** [comment]
I can appreciate that. I'm extremely hesitant to share my 2-year project even privately without brushing up on my legalese first...I would need to talk to a few people first, but I'm aware that it might be the only way.

I will see about creating a second, public project that replicates this. If I'm unable to get that up and running, then I will reach out directly. Thanks for your patience.

**Comment by ShockSlayer** [comment]
Some new information: I was able to finally get crashes with the validation layers active, after disabling the majority of my rendering calls. This happens after attempting to call `vkCmdBindPipeline` in `VULKAN_SetDrawState`


VUID-vkDestroyBuffer-buffer-00922(ERROR / SPEC): msgNum: -464217071 - Validation Error: [ VUID-vkDestroyBuffer-buffer-00922 ] | MessageID = 0xe4549c11 | vkDestroyBuffer():  can't be called on VkBuffer 0xec4bec000000000b[] that is currently in use by VkCommandBuffer 0x1412295a760[]. The Vulkan spec states: All submitted commands that refer to buffer, either directly or via a VkBufferView, must have completed execution (https://vulkan.lunarg.com/doc/view/1.3.280.0/windows/1.3-extensions/vkspec.html#VUID-vkDestroyBuffer-buffer-00922)
    Objects: 0
ERROR: vkQueueSubmit(): VK_ERROR_DEVICE_LOST
VUID-vkCmdPipelineBarrier-commandBuffer-recording(ERROR / SPEC): msgNum: 908748201 - Validation Error: [ VUID-vkCmdPipelineBarrier-commandBuffer-recording ] Object 0: handle = 0x1412296c340, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x362a65a9 | vkCmdPipelineBarrier():  was called before vkBeginCommandBuffer(). The Vulkan spec states: commandBuffer must be in the recording state (https://vulkan.lunarg.com/doc/view/1.3.280.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdPipelineBarrier-commandBuffer-recording)
    Objects: 1
       [0]  0x1412296c340, type: 6, name: NULL
VUID-vkCmdBeginRenderPass-commandBuffer-recording(ERROR / SPEC): msgNum: 1284016627 - Validation Error: [ VUID-vkCmdBeginRenderPass-commandBuffer-recording ] Object 0: handle = 0x1412296c340, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4c8889f3 | vkCmdBeginRenderPass():  was called before vkBeginCommandBuffer(). The Vulkan spec states: commandBuffer must be in the recording state (https://vulkan.lunarg.com/doc/view/1.3.280.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdBeginRenderPass-commandBuffer-recording)
    Objects: 1
       [0]  0x1412296c340, type: 6, name: NULL
VUID-vkCmdBindVertexBuffers-commandBuffer-recording(ERROR / SPEC): msgNum: 94065703 - Validation Error: [ VUID-vkCmdBindVertexBuffers-commandBuffer-recording ] Object 0: handle = 0x1412296c340, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x59b5427 | vkCmdBindVertexBuffers():  was called before vkBeginCommandBuffer(). The Vulkan spec states: commandBuffer must be in the recording state (https://vulkan.lunarg.com/doc/view/1.3.280.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdBindVertexBuffers-commandBuffer-recording)
    Objects: 1
       [0]  0x1412296c340, type: 6, name: NULL
VUID-vkCmdBindVertexBuffers-commandBuffer-recording(ERROR / SPEC): msgNum: 94065703 - Validation Error: [ VUID-vkCmdBindVertexBuffers-commandBuffer-recording ] Object 0: handle = 0x1412296c340, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x59b5427 | vkCmdBindVertexBuffers():  was called before vkBeginCommandBuffer(). The Vulkan spec states: commandBuffer must be in the recording state (https://vulkan.lunarg.com/doc/view/1.3.280.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdBindVertexBuffers-commandBuffer-recording)
    Objects: 1
       [0]  0x1412296c340, type: 6, name: NULL
VUID-vkCmdBindPipeline-commandBuffer-recording(ERROR / SPEC): msgNum: -365328357 - Validation Error: [ VUID-vkCmdBindPipeline-commandBuffer-recording ] Object 0: handle = 0x1412296c340, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xea39881b | vkCmdBindPipeline():  was called before vkBeginCommandBuffer(). The Vulkan spec states: commandBuffer must be in the recording state (https://vulkan.lunarg.com/doc/view/1.3.280.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdBindPipeline-commandBuffer-recording)
    Objects: 1
       [0]  0x1412296c340, type: 6, name: NULL
Exception thrown at 0x00007FFE34BD0F65 (nvoglv64.dll) in application_name.exe: 0xC0000005: Access violation writing location 0x0000000000000000.

**Comment by ShockSlayer** [comment]
I can also provide this, which may be useful: https://gist.github.com/ShockSlayer/0536b550dd1f1b1b1e53d5d30b899cd6

While this doesn't crash; it's a basic SDL3/ImGui example, and when opening the "Examples" drop-down menu, I noticed this was enough to create some validation errors.

**Comment by danginsburg** [comment]
Thanks for the imgui repro.  I pushed a fix for the validation errors: https://github.com/libsdl-org/SDL/pull/9417.  Please let me know if this also fixes your bug.

**Comment by ShockSlayer** [comment]
This does fix the crashing and validation errors for me. Unfortunately there is still one last problem; I'm still getting some white flashing textures:

https://github.com/libsdl-org/SDL/assets/25577726/e5f59660-1f53-4706-8961-290bb08b9b49

This is roughly what I would see sometimes right before the previous crashes. It appears to temporarily stabilize after a short time, probably due to the new fixes. I'm hoping you can eyeball this and get a few ideas, as recreating all of this outside of the game engine will be significantly harder than the imgui example. I can create another issue for this though if needed, since the crashing issue has been solved.

**Comment by danginsburg** [comment]
Unfortunately, I can't really guess what's happening here.  If you can take a capture of a flickering frame in RenderDoc (https://renderdoc.org/) I might be able to figure it out.
